### ISSUE TITLE
Use Case - Financial modelling

### ISSUE THREAD

**Issue by limx0** [python-streamz/streamz#14]
Firstly, this looks super interesting @mrocklin. There is a definite use case in finance / trading - we often build complex DAGs and ideally need some form of streaming service. In the past, I have used Luigi, but it doesn't really fit the streaming model and the scheduler isn't as intelligent as dask.

Some info about the process (skip if you don't care): generally we ingest data from multiple streaming sources, do some transformations or run data through a model, and output multiple streams to different trading strategies. We also need to do some sort of model fitting/backtesting/validation. Often these models or strategies are of varying complexity - some strategies may be able to trade with only one or two inputs (and we want them to be fast) and then others may require more complex calculations or several nodes to complete. 

Ideally (and at a high level) we would like the ability to do the following: 
1. Define a DAG in a simple and flexible way that doesn't require a bunch of boilerplate.
2. Run the DAG historically over some past data to validate our models. Also being able to parameterise -eg, run this for 2017-01-01, 2017-01-02...
3. Update nodes in the DAG, re-run and have the executor only update required data (An extension of this is exceptions - if a node/function breaks, being able to update some code and continue running a pipeline where it left off is a massive plus)
4. Run the DAG in production in some form of streaming fashion, so we can process and transform data live to feed our models. 

Luigi offered most of this, except 
- there was quite a bit of boilerplate to set up dependencies, 
- it was targeted at slower running pipelines and 
- scaling it out was quite a pain. 

I also believe we have most of this with dask. 1. is obvious, 2. is easy, I had a working version of 3. using dask and joblibs memory.cache pretty well. The only missing piece is being able to move that dask graph into production. This could be done by creating a DAG in dask and calling it repeatedly with new data, however in the case of nodes completing at different times, the pipeline becomes as fast as its' slowest part, which isn't ideal when you want paths to complete ASAP.

I suppose my question is, given the information above, do you see this as a potential use case for streams, or should I be working harder to get dask to play how I want it to. I am very keen to contribute if this problem fits into the broader goals streams is trying to achieve. 

If the motivation isn't clear I can try and provide some simple examples of what I mean

**Comment by CJ-Wright** [comment]
IMHO this seems like an awesome use case and is pretty similar to what we are hoping to do with experimental x-ray data processing.
1. Is similar to what I was asking for in #7 (in case this use case does a better job of articulating it)

**Comment by ordirules** [comment]
I like this idea. Sounds like everything is there to do what you need to do using `dask`.

Correct me if I'm wrong, but I think I see two points:
1. Converting from dask to stream
2. Allowing of asynchronous computations (so that the pipeline is not limited to its slowest part)

For the second, streams may help in the asynchronous bit you mention. You could do it by using a `buffer`:
```python
s = Stream()
s.buffer(1000)# where 1000 is some max size you'll allow
# everything else from here is now asynchronous
s.map(otherfunctions)
# etc...
```
Only issue is you may need to add a component in the stream to check that the buffer hasn't filled up, and if yes, then probably block everything.

You'll need to start the `IOLoop` that runs the asynchronous calls somewhere. I'm guessing something like (I haven't tested this but I think something like this should work):
```python
from threading import Thread
th = Thread(target=s.loop.start)
th.daemon = True
th.start()
```

Streams is nice because `buffer` would handle the setup necessary asynchronous calls. I really like that.

Also, if #13 goes through, then delayed objects could be easily passed through the stream with:
```python
@stream_map.register(Delayed)
def stream_map(obj, func, **kwargs):
    return delayed(func)(obj)
# now add compute

data = 1
s = Stream()
s2 = s.map(addone)
s2.map(compute, raw=True).map(print)
s.emit(delayed(data))
```

Converting from dask to stream I think could be easily written as well. (Just loop through tasks and create mappings one by one)

I'm playing around with this, but it is my opinion that the power of streams comes from having control over rates and asynchronous calls (else you could do the rest by iterating over a for loop).

I'm wondering if this resolves your use case or I misunderstood? I'm also interested to see what @mrocklin thinks.

**Comment by mrocklin** [comment]
Sorry for the delay in response (I've been mostly away for the last two weeks).

@limx0 can you expand on the statement below?

> The only missing piece is being able to move that dask graph into production. This could be done by creating a DAG in dask and calling it repeatedly with new data, however in the case of nodes completing at different times, the pipeline becomes as fast as its' slowest part, which isn't ideal when you want paths to complete ASAP.

In particular have you tried using the distributed scheduler's asynchronous computing functionality?  You can submit many graphs at once before the first finishes.  I suspect that you could achieve what you want with that API and a for loop, though I might not fully understand your situation.

For @ordirules 's statement about one key point:

> Converting from dask to stream

We need to be clear that a Dask graph doesn't contain enough information to fully create a stream in any but the most trivial of cases.  I anticipate (perhaps incorrectly) that people will want to establish how multiple input streams are joined together (there are several choices) or how various points in a stream are buffered or bundled (there are several choices).  A dask graph does not contain this information.

So I guess my response here now is @limx0 are you able to achieve what you want using the asynchronous abilities of dask's distributed scheduler?  If so, what common operations do you find yourself doing frequently?  If not then what is missing?

```python
# example
from dask.distributed import Client
client = Client()

all_futures = []
for fn in filenames:
    delayed_values = ...
    futures = client.compute(delayed_values)
    all_futures.append(futures)
```

**Comment by elementace** [comment]
@mrocklin , @ordirules , @CJ-Wright 
I think the largest differentiator is that in the case @limx0 is describing above, he is acting with live streaming data. As in, the environment for which we are pushing information through the DAG is dynamic (not computation of static sets).
