### ISSUE TITLE
Best practice for destroying `sink_to_list` sink

### ISSUE THREAD

**Issue by CJ-Wright** [python-streamz/streamz#147]
Normal sinks return a reference to the node so they can be destroyed, but `sink_to_list` returns the list to which data is being appended. What is the best way of getting a handle on a specific `sink_to_list` node so it can be destroyed?
(Should we consider changing the API to return the sink's reference too?)

**Comment by martindurant** [comment]
Since this is mostly used in testing as a convenience, I think it's fine to leave it as it is. We could add somewhere how to do this by hand and maintain that link:
```
l = []
sink = source.sink(l.append)
```
