### ISSUE TITLE
Can't emit to DataFrame

### ISSUE THREAD

**Issue by dcferreira** [python-streamz/streamz#151]
I'm having problems using the DataFrame class from streamz.
I'm trying the [example from the documentation](https://streamz.readthedocs.io/en/latest/dataframes.html#streaming-dataframes), but it throws an exception when I emit:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-bfd4d3d53c48> in <module>()
----> 1 stream.emit(pd.DataFrame({'name': ['Bob'], 'amount': [6]}))

/tmp/test/lib/python3.5/site-packages/streamz/core.py in emit(self, x, asynchronous)
    257 
    258                 raise gen.Return(result)
--> 259             return sync(self.loop, _)
    260 
    261     def update(self, x, who=None):

/tmp/test/lib/python3.5/site-packages/streamz/core.py in sync(loop, func, *args, **kwargs)
   1175             return gen.with_timeout(timedelta(seconds=timeout), coro)
   1176 
-> 1177     if not loop._running:
   1178         try:
   1179             return loop.run_sync(make_coro)

AttributeError: 'AsyncIOMainLoop' object has no attribute '_running'
```

I created a jupyter notebook with two cells. This is the first one, which executes ok (although the output is empty, and I think it should be "7"):
```python
import pandas as pd
from streamz import Stream
from streamz.dataframe import DataFrame

stream = Stream()
example = pd.DataFrame({'name': ['Alice', 'John', 'Alice'], 'amount': [2, 3, 5]}, index=[0,1,2])
sdf = DataFrame(stream, example=example)

sdf[sdf.name == 'Alice'].amount.sum()
```
The second cell, where I get the exception:
```python
stream.emit(pd.DataFrame({'name': ['Bob'], 'amount': [6]}))
```

To be sure about versions of packages, I created a new virtualenv, where I created the above mentioned notebook:
```bash
dferreira:~$ cd /tmp/
dferreira:/tmp$ virtualenv test
Using base prefix '/home/dferreira/.pyenv/versions/3.5.2'
New python executable in /tmp/test/bin/python3.5
Also creating executable in /tmp/test/bin/python
Installing setuptools, pip, wheel...done.
dferreira:/tmp$ cd test/
dferreira:/tmp/test$ source bin/activate
(test) dferreira:/tmp/test$ pip install jupyter streamz pandas
[...]
(test) dferreira:/tmp/test$ jupyter notebook
```
versions:
pandas==0.22.0
streamz==0.3.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0

Am I doing something wrong?

**Comment by dcferreira** [comment]
I should also mention, I tried reverting tornado to version 4.5.3, and it also doesn't work, but it has a different problem. Instead of throwing an exception, it just gets stuck here:
https://github.com/mrocklin/streamz/blob/9052bccac20f16488f859e603e28d6501e01aafb/streamz/core.py#L1152-L1153

I also tried commenting out the check of `loop._running` (when using tornado==5.0), and it then gets stuck in the same place, instead of throwing the exception in the first post.

**Comment by dcferreira** [comment]
As a workaround, using ``asynchronous=True`` when calling ``emit`` doesn't seem to execute the problematic part of the code.

Still not sure if the behavior when ``asynchronous=False`` (default) is intentional, so leaving the issue open.

**Comment by mrocklin** [comment]
Yeah, the asynchronous stuff generally needs to be cleaned up.  This is
blocking usability for a few cases.

**Comment by opensourcechris** [comment]
I'm working on the changelog and some doc examples while I read the code. Which use cases does this affect? I can add some doc updates to cover this situation.

**Comment by martindurant** [comment]
ref https://github.com/mrocklin/streamz/pull/152
