### ISSUE TITLE
Displaying a streamz dataframe in JupyterLab overrides output everywhere

### ISSUE THREAD

**Issue by philippjfr** [python-streamz/streamz#161]
When displaying a streamz dataframe in JupyterLab it seems to display nicely at first, dynamically updating as expected. However it seems all subsequent cells will also display the streaming dataframe output no matter if it is actually displayed in the cell.

In the example below I'm simply display the ``Random`` example dataframe and as you can see subsequent cells also display the output despite the fact that I'm just trying to display some integers in them:

![screen shot 2018-04-04 at 7 28 57 pm](https://user-images.githubusercontent.com/1550771/38326852-c2678ebe-383e-11e8-9995-ac445bdc0313.png)

These are the versions I have installed locally:

streamz == '0.3.0'
jupyterlab == '0.31.12'

**Comment by mrocklin** [comment]
Reported upstream here: https://github.com/jupyterlab/jupyterlab/issues/4319

**Comment by martindurant** [comment]
No longer an issue.
