### ISSUE TITLE
[Q] Real time streaming

### ISSUE THREAD

**Issue by hofab** [python-streamz/streamz#171]
Hi,
What a cool project you got here, I really enjoy it.
Nonetheless, I have a question how to use it with real time data. I can't figure out how to get data correctly to the stream.

In my example, I want to push one sample at a time to the stream and display the complete curve, like in the streaming example. 
```
%matplotlib notebook
from time import sleep
from streamz import *
from streamz.dataframe import Random, DataFrame
import pandas as pd

source = Stream()
samples = pd.DataFrame({'x':[],'y':[]})
sdf = source.to_dataframe(example=samples)

for i in range(5):
    source.emit(pd.DataFrame({'x': [i], 'y' :[i]}))
    sleep(0.15)
p = (DataFrame({'raw': sdf.x}).plot(width=700))
sdf.x.sum()
```
Unfortunately, I can't get any output. The diagram is drawn, but the line is not drawn. Additionally, calculating the sum leads to nothing. Any suggestions?

I just realized, that I get an error in my jupyter notebook terminal:

```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fa3f42fda60>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/fhof/.local/lib/python3.5/site-packages/streamz/dataframe/core.py", line 187, in _
    cds.stream(d, backlog)
  File "/home/fhof/.local/lib/python3.5/site-packages/bokeh/models/sources.py", line 343, in stream
    self._stream(new_data, rollover)
  File "/home/fhof/.local/lib/python3.5/site-packages/bokeh/models/sources.py", line 455, in _stream
    self.data._stream(self.document, self, new_data, rollover, setter)
  File "/home/fhof/.local/lib/python3.5/site-packages/bokeh/core/property/containers.py", line 383, in _stream
    data = np.append(self[k], new_data[k])
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/function_base.py", line 5152, in append
    return concatenate((arr, values), axis=axis)
TypeError: invalid type promotion
```

I would appreciate any help right now.

**Comment by hofab** [comment]
Thanks @martindurant, but there must be still some disconnect.
I assume everything is appended to sdf, but sdf has only one element after the loop.

Are my inputs not written into sdf, I don't understand what I am missing.

**Comment by martindurant** [comment]
Perhaps you want `df = sdf.window(5).full()`? In practice, you would want to *do* something with the accumulated df, rather than emit all of it every time.

**Comment by hofab** [comment]
Sorry, I don't get it right now. 
If I call emit, is my data pushed onto the stream? That is my understanding at least.

In you example if I print(sdf) it returns:
```
DataFrames - elements like:
   x  y
0  0  0
```
So there is nothing to window, or wait until it is full. I think my problem is, that sdf. Is sdf not populated with my 5 data frames? 
Where is all my data stored? Is the previous data lost after an emit? 

From the example:
`source = Random(freq='5ms', interval='100ms')`
Random returns a data frame of the size (100/5) = 20, right?
But I want to replace Random with my input, therefore I translate my source stream to a data frame of the kind samples, and store it in sdf. I would think this action is performed on every emit, so that I have a stream of data frames, in my case just one sample in sdf. 

But my sdf is always 0,0 - the data frame of my samples. 

I think I need to write a function like Random() that translates my values into a data frame.

**Comment by martindurant** [comment]
Instead of printing `dfs`, just allow `df` to repr in the notebook by leaving putting it at the end of a cell. You *could* do `df.stream.sink(print)`, if you wish. Anyhow, `dfs` emits a dataframe from its input every time it gets input, you need to collate them yourself. `Random` in your example does not produce a value every 5ms, it produces a full dataframe every 100ms which happens to be a timeseries with the given frequency.

**Comment by hofab** [comment]
Thank you for your help. That is what I was thinking. 
But how does the stream = source get translated to sdf or df?


```
%matplotlib notebook
from time import sleep
from pymaint import *
from streamz import *
from streamz.dataframe import Random, DataFrame
import pandas as pd

source = Stream()
samples = pd.DataFrame({'x':[0],'y':[0]})
sdf = DataFrame(source, example=samples)
df = sdf.window(5).full()
source.sink(print)

for i in range(5):
    source.emit(pd.DataFrame({'x': [i,i,i], 'y' :[i,i,i]}))
    #source.emit(pd.DataFrame({'x': [i], 'y' :[getFieldFromModule(demoModule,1,1)]}))
    sleep(0.15)

sdf
df
```
Leads to:
```
   x  y
0  0  0
1  0  0
2  0  0
   x  y
0  1  1
1  1  1
2  1  1
   x  y
0  2  2
1  2  2
2  2  2
   x  y
0  3  3
1  3  3
2  3  3
   x  y
0  4  4
1  4  4
2  4  4
```

There is no clearly no output for `sdf` or `df`. What we see is the output of source.sink(print), I have a hard time to understand where my disconnect comes from.

**Comment by martindurant** [comment]
Consider 
```
source = Stream()
samples = pd.DataFrame({'x':[0],'y':[0]})
sdf = DataFrame(source, example=samples)
df = sdf.window(5).full()
df.stream.sink(print)
```

Anyway, it is clear that our documentation/examples need to be revamped. If you figure things our from your relatively newcomer point of view, you will probably be in the best position to think about how best to describe what is really going on.

**Comment by robmarkcole** [comment]
HI @martindurant I am struggling with a related issue, but in my case I am collecting data from a real sensor [here](https://github.com/robmarkcole/Useful-python/blob/master/Pyserial/pyserial.ipynb). Currently my loop has `time.sleep` which means there is no graph display until the end of the data acquisition loop. Is there a nice example how I should plot data in real time considering the sleep?

**Comment by martindurant** [comment]
@robmarkcole , I assume you would want to implement a class that works using coroutines, so it can be called asynchronously, like [from_textfiles](https://github.com/mrocklin/streamz/blob/master/streamz/sources.py#L41)

**Comment by martindurant** [comment]
@robmarkcole , did you get anywhere with this?

@hofab , I think your issue generally points to our needing to be much clearer about the flow of information and the role of the different types of streams in the docs. I think this specific issue, which is now pretty old, can be safely closed.

**Comment by robmarkcole** [comment]
@martindurant I did not spend any more time on this unfortunately
