### ISSUE TITLE
ENH: warn user if combining dask streamz with not dask streamz

### ISSUE THREAD

**Issue by CJ-Wright** [python-streamz/streamz#172]
Problems seem to occur if a dask stream are combined with not a dask stream (causing futures to not be evaluated when running functions). It might be nice to warn users if they have subscribed a dask stream to a non dask stream without a scatter/gather.

**Comment by martindurant** [comment]
You mean things like `union`, where multiple upstreams are present?

**Comment by CJ-Wright** [comment]
Yes (although I ran into this with things like `combine_latest` combining a dask and not dask stream.

**Comment by mrocklin** [comment]
If i were to use Stream.combine_latest on a DaskStream i would expect to get a stream with futures in it.  Is this what you're getting?  If so then is this something that you consider to be an error?

**Comment by CJ-Wright** [comment]
Yes, that is what I am getting (and hence the confused issue against dask, sorry). I think the use case for this, where users want to operate on futures rather than the actual data is a fairly limited one, and that this issue can be rather difficult to diagnose, especially in larger pipelines. Having the option to warn seemed like a reasonable compromise between outright raising and causing errors inside the operations themselves when they receive futures and expected data.

One could also make an argument for this to go as a gotcha somewhere in the docs.

**Comment by mrocklin** [comment]
> One could also make an argument for this to go as a gotcha somewhere in the docs.

Yeah, if it's reasonable to want to do this then I don't think that we should have it err.

**Comment by mrocklin** [comment]
I recognize the value of steering users towards common behaviors though.  I don't have a good answer on how to balance between these.

**Comment by martindurant** [comment]
@CJ-Wright , suggest closing, since your "gotcha" was merged.

**Comment by CJ-Wright** [comment]
Thank you!
