### ISSUE TITLE
How to plot streaming dataframe?

### ISSUE THREAD

**Issue by changwally** [python-streamz/streamz#192]
Hi, 

awesome project! I'm having trouble plotting bokeh plots - 
I tried the following in jupyter notebook:

```
from streamz.dataframe import Random, DataFrame
source = Random(freq='5ms', interval = '100ms')
sdf = (source - 0.5).cumsum()
DataFrame({'raw':sdf.x, 'smooth':sdf.x.rolling('100ms').mean()}).plot(width=700)
```
but kept getting the following exception:
```
anaconda2/envs/py35/lib/python3.5/site-packages/numpy/lib/function_base.py", line 4528, in append
    return concatenate((arr, values), axis=axis)
TypeError: invalid type promotion

```
is there a particular numpy / pandas version i should be using?
I am using:

```
pandas                    0.23.3          py35h6440ff4_0    anaconda
numpy                     1.15.0           py35h648b28d_0    anaconda
numpy-base            1.15.0           py35h8a80b8c_0    anaconda
```

**Comment by martindurant** [comment]
You shouldn't normally cal `DataFrame` like that - it expects as input a stream and example dataframe, not a dictionary of streaming series. Perhaps you want `sdf.assign` or `sdf.rolling()` with a more complicated aggregation step. As far as plotting, see https://hvplot.pyviz.org/user_guide/Streaming.html

**Comment by danilomo** [comment]
In the current version there's no hvplot() function anymore. How can I plot a DataFrame in streamz 0.5.0?

**Comment by martindurant** [comment]
@danilomo , did you do `import hvplot.streamz`? That should populate the 

You can always call `hvplot.hvPlot(df)` directly.

**Comment by danilomo** [comment]
Works like a charm, thank you!

**Comment by frozenranger** [comment]
Hey guys,

Just a quick question, Im trying the most simple streaming example but it isn't working? The random function isn't streaming any data?

import hvplot.streamz
from streamz.dataframe import Random


df = Random(interval='200ms', freq='50ms')


print(df)

Random - elements like:
Empty DataFrame
Columns: [x, y, z]
Index: []

how do I get it to generate data?

**Comment by martindurant** [comment]
```python
from streamz.dataframe import Random
df = Random(interval='200ms', freq='50ms')
df
```
in a jupyter notebook does exactly what you might imagine. Streamz objects generally know how to display themselves and update automatically - but the `print` function evaluates exactly when you call it and produces a string (which does not know how to update itself.

If you want graphical output, see examples like
- https://panel.holoviz.org/reference/panes/Streamz.html
- http://holoviews.org/user_guide/Streaming_Data.html
- https://panel.holoviz.org/reference/panes/DataFrame.html
