### ISSUE TITLE
Generate trivial DaskStream classes

### ISSUE THREAD

**Issue by CJ-Wright** [python-streamz/streamz#194]
Would it be possible to generate the trivial `DaskStream` classes (eg. zip)? There seems to be a lot of boilerplate associated with those nodes and it would be great if new `DaskStream` classes were added when new core classes were added.

Additionally this may help with making having a more backend agnostic approach to external task managing for streamz. For instance one could try to replace `Dask` with `concurrent.futures` executors since both have a similar interface (or anything else which has a futures driven interface).

**Comment by mrocklin** [comment]
How trivial are they?  What would you expect from zipping two dask
streams,  a tuple of futures or a future of tuples?  This seems non-trivial
to me, which is probably why it wasn't implemented.

**Comment by CJ-Wright** [comment]
I am expecting what we currently have: https://github.com/mrocklin/streamz/blob/master/streamz/dask.py#L189

**Comment by mrocklin** [comment]
Hrm, that's surprising.  So your proposal is to automate that process?
What is objective?  Reduce maintenance time?  How expensive is it currently
to wrap a core class?

**Comment by CJ-Wright** [comment]
Two main objectives:
1. Reduce maintenance
1. Work towards having multiple parallel backends.

It seems that much of the `dask` parts of `DaskStream` could be expanded to `concurrent.futures.Executor` subclasses with some tweaks. Being able to auto generate parallel stream classes could be a good first step in that direction since it would scale well with other backends.

**Comment by martindurant** [comment]
Closing this now. If a proposal implementing what is here comes in, we can review it and discuss the pros and cons.
