### ISSUE TITLE
KeyError: '<lambda>-2307dc7b2c82af5955af3f6229602312'

### ISSUE THREAD

**Issue by tpawlowski** [python-streamz/streamz#206]
```
distributed.worker - ERROR - '<lambda>-2833aefd7b56dbf98105d8c710bba769'
Traceback (most recent call last):
  File "/Users/tpawlowski/workspace/dokstud/alpenglow/venv_streamz/lib/python3.6/site-packages/distributed/worker.py", line 2021, in release_key
    self.dependents[dep].remove(key)
KeyError: '<lambda>-2833aefd7b56dbf98105d8c710bba769'
Future exception was never retrieved
future: <Future finished exception=KeyError('<lambda>-2833aefd7b56dbf98105d8c710bba769',)>
```

Hello, I have implemented a pipeline including "scatter" and "gather". I am trying to run it on Dask, but I have problem with getting rid of the error above. Anybody has any clues what could go wrong?

**Comment by mrocklin** [comment]
Are you able to provide a minimal example that reproduces this error?

**Comment by tpawlowski** [comment]
the failing pipeline looks like follows:
```
numbers = Stream()
part_1 = numbers.scatter().map(...).accumulate(...).map(...)
part_2 = numbers.scatter().map(...).union(part_1).gather().sink(print)
```
accumulate is an long running task. the error is raised from one of the map calls - not always the same.

**Comment by mrocklin** [comment]
If you're able to create a small copy-pastable example with dummy functions
that was both as simple as possible but also reproduced the error that
would help a great deal in trying to resolve the problem.

**Comment by tpawlowski** [comment]
I have edited my previous post. A simple example which is failing looks as follows:
```
client = Client('127.0.0.1:8786')
numbers = Stream()
part_1 = numbers.scatter()
part_2 = numbers.scatter().union(part_1).buffer(8).gather().sink(print)
for number in range(10):
  numbers.emit(number)

try:
  time.sleep(3)
finally:
  client.close()
```

**Comment by mrocklin** [comment]
Thank you for the minimal example.  I've worked this down to a failure
within Dask about scattering the same data concurrently here:
https://github.com/dask/distributed/pull/2244

I won't have time to resolve it this week, but may look into it in the next
few weeks.

Short term I suspect that you would be happier if you scattered a stream
only once (this would be more efficient anyway).

**Comment by tpawlowski** [comment]
Thank you!
Single scatter approach fixed the previous example:
```
import time
from streamz import Stream
from dask.distributed import Client

def test_map(x):
    print("{} {}".format(x, type(x)))
    time.sleep(0.1)
    return x

client = Client('127.0.0.1:8786')
numbers = Stream()
scattered_numbers = numbers.scatter()
part_1 = scattered_numbers.map(test_map).buffer(8)
part_2 = scattered_numbers.union(part_1).buffer(8).gather().sink(print)
for number in range(10):
  numbers.emit(number)
```

The problem is in my case I was actually doing filtering before the mapping, and I haven't figured out how to introduce filters and flat-maps in the scattered stream. Is there a way to implement the following in an efficient way?
```
import time
from streamz import Stream
from dask.distributed import Client

def test_map(x):
    print("{} {}".format(x, type(x)))
    time.sleep(0.1)
    return x

def test_filter(x)
  return x % 2 == 0

client = Client('127.0.0.1:8786')
numbers = Stream()
part_1 = numbers.filter(test_filter).scatter().map(test_map).buffer(8)
part_2 = numbers.scatter().union(part_1).buffer(8).gather().sink(print)
for number in range(10):
  numbers.emit(number)
```

**Comment by tpawlowski** [comment]
I have reproduced the error with simpler code, which did not involve double scatter:
```
from streamz import Stream
from dask.distributed import Client


def sample(image_id):
    _, version = image_id
    if ((version + 1) * (3 - 1) // 7) > (version * (3 - 1) // 7):
        return [image_id]
    return []

client = Client('127.0.0.1:8786')
image_ids = Stream()
part_1 = image_ids.scatter().map(sample).buffer(10).gather().sink(print)
for stripe in range(3):
    for version in range(7):
        image_ids.emit((stripe, version))
```

The error remains the same: 
```
distributed.worker - ERROR - 'sample-9ac55ea766a57d498a4e83c366c76d7d'
Traceback (most recent call last):
  File "/Users/tpawlowski/workspace/dokstud/alpenglow/venv_streamz/lib/python3.6/site-packages/distributed/worker.py", line 2021, in release_key
    self.dependents[dep].remove(key)
KeyError: 'sample-9ac55ea766a57d498a4e83c366c76d7d'
Future exception was never retrieved
future: <Future finished exception=KeyError('sample-9ac55ea766a57d498a4e83c366c76d7d',)>
```

Any idea what could be broken in here?

**Comment by martindurant** [comment]
This was some time ago...
I tried your code, above, and saw no exception; would you mind retrying with the latest master version (with distributed also updated)?

**Comment by martindurant** [comment]
Closed as stale
