### ISSUE TITLE
[Q] Event_loop from asyncio

### ISSUE THREAD

**Issue by bsdis** [python-streamz/streamz#208]
In the documentation it says that to make a stream run asynchronous, we need to use a tornado IOLoop.

from streamz import Stream
from tornado.ioloop import IOLoop

@gen.coroutine
def f():
    .....
IOLoop().run_sync(f)

This is nice, but I am using asyncio.get_event_loop().
Can I somehow integrate this event_loop with streamz framework also?

Thanks

**Comment by CJ-Wright** [comment]
I think you can pass a `loop` kwarg with the io loop to the stream

**Comment by mrocklin** [comment]
In version five and above Tornado now uses the asyncio event loop.  You
might consult their documentation for how to get the asyncio event loop out
of the tornado event loop.

**Comment by martindurant** [comment]
Both answers above are valid, so closing this.
