### ISSUE TITLE
streamz and toolz compatability

### ISSUE THREAD

**Issue by bwengals** [python-streamz/streamz#214]
How compatible are `streamz` and `toolz`?  I am trying to use the `reduceby` operation of `toolz` as described in the [streaming analytics](https://toolz.readthedocs.io/en/latest/streaming-analytics.html) section of the docs with the `streamz` library.  Naively, I tried various things similar to:

    from toolz import reduceby
    from streamz import Stream

    def iseven(n):
        return n % 2 == 0 

    def add(x, y):
        return x + y

    source = Stream()
    out = reduceby(iseven, add, source)
    out.emit(print)

Is there a straightforward way to use these libraries together?  In the case of `reduceby`, should it be used within a call to `streamz` `accumulate`?

**Comment by mrocklin** [comment]
Short answer is no.  They have different code paths to accomplish the same goals.

**Comment by bwengals** [comment]
Gotcha, thanks!  I saw a couple uses of toolz internally, makes sense.

**Comment by martindurant** [comment]
Closing this as answered.
People are generally encourages to implement missing toolz behaviour for streamz, if it is appropriate and there is a use case.
