### ISSUE TITLE
move to dask org

### ISSUE THREAD

**Issue by martindurant** [python-streamz/streamz#218]
Streamz should be generally useful for people. Can we please move it? Dask org makes sense because of the history of this project, and because of the direct links to dask functionality.

@mrocklin

**Comment by CJ-Wright** [comment]
I'm currently maintaining ``rapidz`` and could try to merge back my changes to unify under ``streamz``.

**Comment by martindurant** [comment]
I am discussing with CJ about backporting rapidz, so that between us (CJ, myself and maybe you), we can maintain at least better than now

**Comment by mrocklin** [comment]
The sense I got was that many of CJ's changes were more specific than I was comfortable with.  CJ's need for a fork isn't just lack of maintenance.

**Comment by martindurant** [comment]
A PR containing those changes would be worth discussion for sure.

**Comment by mrocklin** [comment]
Sure, PRs are always welcome, but several of CJ's recent PRs were, I think, too tailored to his specific application, and so were rejected.  If there are general core improvements then great, I'd be all for those.  

@martindurant if you haven't already you might want to go through the recent PRs, open and closed, and see discussion there.

**Comment by mrocklin** [comment]
Also, I notice that there are several unanswered issues in the issue tracker.  If people are interested in maintaining this library then triaging and responding to those would probably be a good place to start.  I'm not saying that people have to solve everyone's problem, but people definitely need to get some response that explains what's going on before this library would be considered maintained.
