### ISSUE TITLE
Performance metrics for from_textfile_batched()

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#235]
Just added the from_textfile_batched() method, which is DaskStream compatible. 

Some performance metrics (by varying batch-size as well) I gathered, after pulling in skmatti's cuDF integration: 

Throughput w/ Dask & w/ cuDF aggregations, on Quadro P6000: 10MBps, as opposed to the simple from_textfile() which gave ~1MBps.  
Throughput w/ Dask & w/ cuDF aggregations, on T4: 12.5MBps.

**Comment by martindurant** [comment]
Does it make a difference how common line terminators are in the input?

**Comment by chinmaychandak** [comment]
Not sure I understand your question. The batches are just based on the delimiter and batch size specified.

**Comment by martindurant** [comment]
I am thinking, more terminators, more individual messages in the non-batched version, so that would affect the throughput.

**Comment by chinmaychandak** [comment]
Yes, that is definitely true. The non-batched version simply emits a single element/message downstream, which lowers throughput (in terms of number of messages/sec). Ideally, when the message size is a little lower, emitting a batch of messages downstream helps.
