### ISSUE TITLE
Test on dask stream

### ISSUE THREAD

**Issue by xray1111** [python-streamz/streamz#239]
I run this simple test code on dask stream, it appears that the dask stream doesn't run parallel but still serial, like the basic stream, I'm not sure if I was making a mistake on the usage of dask stream:

```
from dask.distributed import Client
from streamz import Stream
import time

client = Client(processes=False)

def inc(x):
    time.sleep(1)
    return x + 1

source = Stream()
a = source.scatter().map(inc).gather().sink(print)

source.visualize(rankdir='LR')
```
![Unknown](https://user-images.githubusercontent.com/13399784/55680304-ba538b00-594a-11e9-876c-36b546f07980.png)

`client`

![未命名](https://user-images.githubusercontent.com/13399784/55680380-54b3ce80-594b-11e9-9241-871b3fe3b34f.png)

```
%%time
for i in range(5):
    source.emit(i)
```
```
1
2
3
4
5
CPU times: user 495 ms, sys: 64 ms, total: 559 ms
Wall time: 5.11 s
```

**Comment by CJ-Wright** [comment]
You need to use a buffer node see the documentation here https://streamz.readthedocs.io/en/latest/dask.html#parallel-execution

**Comment by xray1111** [comment]
Thank you @CJ-Wright , it really works!
But the buffer method seems a little confusing, from the API document it's not very clear this method should be called following scattering. Would you please give some more detailed description or some example code? 

Another question: suppose if I have 2 forked streams from the source basic stream now, each stream holds different kinds of data, and I need to handle this 2 streams  using 2 or more threads/processes separately, because I want different threads/processes deal with different data, and importantly, I want the 2 streams be handled sequentially. What is your suggestion to this scenario? Below is my code, do you think it's all right?

```
from dask.distributed import Client
from streamz import Stream
import time

client = Client()

def inc(x):
    time.sleep(1)
    return x + 1

def double(x):
    time.sleep(1)
    return x * 2

source = Stream()
a = source.filter(lambda x: x%2 == 0).scatter().buffer(1).map(inc).gather().sink(print)
b = source.filter(lambda x: x%2 != 0).scatter().buffer(1).map(double).gather().sink(print)

%%time
for i in range(10):
    source.emit(i)
```

**Comment by CJ-Wright** [comment]
The buffer goes right before the gather.
The pipeline in your example should handle each piece of data in its own worker, so long as the buffer node is moved.

**Comment by xray1111** [comment]
If there is a buffer node in the pipeline, the data will be handled concurrently:
```
...
a = source.filter(lambda x: x%2 == 0).scatter().buffer(1).map(inc).gather().sink(print)
b = source.filter(lambda x: x%2 != 0).scatter().buffer(1).map(double).gather().sink(print)
...
```
![image](https://user-images.githubusercontent.com/13399784/55692329-7360a680-59d9-11e9-8c4d-5dcc4e19c3d5.png)

But if I remove the buffer node as below, the result seems like only 1 worker could be executed at the same time:
```
...
a = source.filter(lambda x: x%2 == 0).scatter().map(inc).gather().sink(print)
b = source.filter(lambda x: x%2 != 0).scatter().map(double).gather().sink(print)
...
```
![image](https://user-images.githubusercontent.com/13399784/55692367-e66a1d00-59d9-11e9-8d8f-983f509590e3.png)

**Comment by CJ-Wright** [comment]
You need the buffer right before the gather step.

```python
a = source.filter(lambda x: x%2 == 0).scatter().map(inc).buffer(10).gather().sink(print)
b = source.filter(lambda x: x%2 != 0).scatter().map(double).buffer(10).gather().sink(print)
```

**Comment by xray1111** [comment]
Thanks @CJ-Wright ! I test the code and it works fine!

But I found another problem: after scatter() is called and the current stream turns into a dask stream, filter() can never be called, or it will report an error (seems like we couldn't filter on future). What is the proper way to do some filtering work in a dask stream? or do I have to avoid this kind of things?

```
a = source.filter(lambda x: x % 2 == 0)
                    .scatter()
                    .map(inc)
                    .filter(lambda x: x % 3 == 0)
                    .buffer(10).gather().sink(print)
```

```
...

<ipython-input-2-3a40c70eb1bd> in filter_func(x)
     12 
     13 def filter_func(x):
---> 14     if x % 3 == 0:
     15         return True
     16     return False

TypeError: unsupported operand type(s) for %: 'Future' and 'int'
```

**Comment by CJ-Wright** [comment]
Parallel filtering is not implemented in streamz. If you want you could use [rapidz](https://github.com/xpdAcq/rapidz) which has some support, although there are some corner cases with zip and filter that do not work.

**Comment by martindurant** [comment]
I haven't looked at the implementation in rapidz, but you could hack a solution right now, but using the dask-stream map with a function like 
```
.map(lambda x: True if x%2 == 0 else None)
```
and then using the regular, non-dask filter
```
.filter(lambda x: x.type is bool)   # this works on the futures
```

Alternatively, and probably better, you can filter *batches* by mapping
```
.map(lambda x: [y for y in x if condition(y)])
```
(this is a lot like working with `dask.bag`).

**Comment by martindurant** [comment]
Clarification here: dask will work nicely to filter when you are passing around batches rather than individual events - you cannot know the truthiness of a future, but you can iterate over its contents in a task. Sure, you can end up with empty batches sometimes, but that would probably achieve what is required.

My previous comment (now deleted, because the detail was wrong) about polling the status of a Future *could* be made to work with a little careful thought (using async wait on future or add_done_callback?).

In any case, whilst the question on filtering is valid, the original issue here has been resolved, so I am closing this.
