### ISSUE TITLE
What is difference between .emit() and ._emit()

### ISSUE THREAD

**Issue by MikeChenfu** [python-streamz/streamz#256]
I am a new guy to the Streamz. I just try some examples and find ._emit() has a good performance than .emit(). I really appreciate if someone can give me some details about them.

**Comment by CJ-Wright** [comment]
`_emit` is a very simple implementation, all it does is calls `.update` for all the currently subscribed downstreams collates the results and then returns the results.

`emit` is a much more advanced implementation, which takes into account if the pipeline is being run asynchronously and handles the loop synchronization, couroutine generation, and such. 

If you are expecting to use/support the async aspects of the library you should use `.emit`.

How different is the performance? Can you post a profile of the pipeline?

**Comment by martindurant** [comment]
To be sure, the "performance" will very likely depend upon what your pipeline is doing, and how you have set it up. In some circumstances (no async/ioloops), `emit` just calls `_emit`. If you are running async, however, each subsequent task in `emit` will generally be scheduled on the next ioloop tick, rather than running in blocking mode as in `_emit`.

**Comment by MikeChenfu** [comment]
Thanks @CJ-Wright and @martindurant. In my understanding, theoretically `emit` should have a better performance than `_emit`. But my result does not show that. 

I process 50 files on two dask-workers in my code.

Here is the result I use `emit`. It consumes 90 seconds totally.
<img width="1126" alt="Screen Shot 2019-06-12 at 9 26 46 AM" src="https://user-images.githubusercontent.com/17817768/59360578-f5c95780-8cf5-11e9-843d-580afb1abfe4.png">

Here is the result I use `_emit`. It consumes about 40 seconds and It can be found that there is overlap between reading files and kernel operations.
<img width="994" alt="Screen Shot 2019-06-12 at 9 23 24 AM" src="https://user-images.githubusercontent.com/17817768/59360773-58baee80-8cf6-11e9-8213-bf4f8162b642.png">

**Comment by martindurant** [comment]
`emit()` calls `_emit()`, so no way it could be more efficient https://github.com/python-streamz/streamz/blob/master/streamz/core.py#L306

It would be interesting to find out what is happening during those white stripes: I assume this is back-pressure in action, the system is waiting for futures to become finished and gathering results before firing off more work.

**Comment by MikeChenfu** [comment]
@martindurant I am also curious about these white stripes.
Besides, I just tried `.emit(fn,asynchronous=True)`. I got a good performance like`_emit`'s result. Is it possible '.emit' treat the process as a synchronous process? I process 50 csv files in my code.

Here is my code to read files.
```python
async def f():
    for fn in glob.glob('data/*.csv'):
        source.emit(fn,asynchronous=True) 
IOLoop.current().add_callback(f)
```

**Comment by CJ-Wright** [comment]
Would it be possible to post the pipeline you are using?

**Comment by mrocklin** [comment]
I suspect that by calling _emit you're effectively ignoring backpressure.
My guess is that you want a `buffer` somewhere in your pipeline.

**Comment by MikeChenfu** [comment]
@CJ-Wright Here is the graph regarding to the workflow.
<img width="712" alt="Screen Shot 2019-06-12 at 11 15 12 AM" src="https://user-images.githubusercontent.com/17817768/59368338-9f631580-8d03-11e9-9cd6-c8190e3f9e1b.png">

**Comment by CJ-Wright** [comment]
Yep, @mrocklin is correct, you need a buffer before your gather nodes so multiple things can be processed at once. Otherwise the pipeline will wait for the computation to be finished before the next is processed.

**Comment by MikeChenfu** [comment]
@CJ-Wright @mrocklin Yeah, get a better result. Is there any tips to set the size of `buffer`? I try different size of `buffer` and get the different performance. 
<img width="712" alt="Screen Shot 2019-06-12 at 11 31 11 AM" src="https://user-images.githubusercontent.com/17817768/59369334-d508fe00-8d05-11e9-8ce9-58d5650d689a.png">

**Comment by CJ-Wright** [comment]
The size of the buffer depends on how much compute and ram you have available. I usually go with larger numbers and let dask figure it out.

**Comment by CJ-Wright** [comment]
I think this is mostly resolved. Discussion of buffer size should most likely be an independent issue (and a PR into the docs if we are able to come up with a heuristic approach).

@MikeChenfu please feel free re-open if you need more help with this issue.
