### ISSUE TITLE
DaskStream fails on cudf rolling-over-time operations. 

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#261]
Below is an example to reproduce the "ValueError: window must be an integer for non datetime index" when I try to do rolling over time operations in cudf. 

Surprisingly, the error does not appear if I replace DaskStream() with Stream(). Also, if I just use client.submit() and compute the same rolling over time function, it goes through.

Not sure what the problem with DaskStream is.

```
import cudf
import pandas as pd
import numpy as np
from streamz import Stream, DaskStream
from streamz.dataframe import DataFrame

index = pd.date_range(start='2017-01-01', periods=10, freq='0h30min')
df = cudf.DataFrame({'x': np.arange(len(index))}, index=index)

from distributed import Client, LocalCluster
cluster = LocalCluster()
client = Client(cluster)
client.get_versions(check=True)
client

stream=DaskStream()
sdf = DataFrame(stream=stream, example=df)
roll = getattr(sdf.x.rolling("1h"),'mean')()
L = roll.stream.gather().sink_to_list()
assert len(L) == 0

for i in range(0, len(df), 5):
    sdf.emit(df.iloc[i:i+5])
    
print(cudf.concat(L))
```

**Comment by CJ-Wright** [comment]
What happens if you emit into stream?

**Comment by CJ-Wright** [comment]
What happens if you emit into stream?

**Comment by chinmaychandak** [comment]
@CJ-Wright I'm not sure I understand. If I replace `stream=DaskStream()` with `stream=Stream()`, everything works fine.

**Comment by CJ-Wright** [comment]
I think the problem is that you are emitting into something expecting dask futures, since it is subscribed to a `DaskStream`, but you are handing is dataframes. I would try:
```python
local_stream=stream()
stream = local_stream.scatter()
...
for i in range(0, len(df), 5):
    local_stream.emit(df.iloc[i:i+5])
```

**Comment by chinmaychandak** [comment]
I don't think that is the problem. 

If I replace the cudf dataframe with a pandas dataframe, everything seems to work fine, and I get the correct result.

**Comment by chinmaychandak** [comment]
Closing this issue. Seems it was a cudf issue that was fixed last week: https://github.com/rapidsai/cudf/pull/2311
