### ISSUE TITLE
Index name lost during groupby aggregates on Streamz Dataframes.

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#266]
I am trying to do a simple groupbySum using Streamz Dataframes over cudf Dataframes. I am getting an issue wherein the result is correct, but the index name ('x' in this case) is lost. This issue is not seen with Pandas. 

I am trying to peruse through the code to see where I would have to make changes to make this work. It would be great if someone could help me out as to where exactly the GroupBy class methods do the index name check happen? 

The code to reproduce the bug is:
 
```
from streamz import Stream
from streamz.dataframe import DataFrame
import cudf
import numpy as np
import pandas as pd

df = cudf.DataFrame({'x': (np.arange(10) // 2).astype(float), 'y': [1.0, 2.0] * 5})

stream = Stream()
a = DataFrame(example=df.iloc[:0], stream=stream)

def f(x):
    return x.groupby('x').sum()

L = f(a).stream.gather().sink_to_list()

a.emit(df.iloc[:3])
first = df.iloc[:3]

print(L[0])
print(f(first))
```

The outputs I get are pasted below.
```
       y
0.0  3.0
1.0  1.0
       y
x       
0.0  3.0
1.0  1.0
```

**Comment by martindurant** [comment]
Is this also true with Pandas instead of cudf? It would help with debugging to keep with the simpler dependency.

**Comment by chinmaychandak** [comment]
@martindurant No, this issue isn't seen with Pandas. That's why debugging it is a little more complex. I'd completely understand if you are not able to test this snippet. :( 

Where exactly the GroupBy class/methods in the dataframe folder consider 'x' to be the new index name is not clear to me — maybe you guys can help me out.

**Comment by martindurant** [comment]
I guess check that groupy does the right thing for the cudfs without streamz first, then investigate how the "example" df gets manipulated.

**Comment by jsmaupin** [comment]
It seems to come from `GroupbySum` in the `initial(...)` method. A data frame with an index gets passed into `self.grouped(...)`, but when `.sum()` is called, the return value is without an index.

```python
return self.grouped(new.iloc[:0], grouper=grouper).sum()
```

**Comment by chinmaychandak** [comment]
> I guess check that groupy does the right thing for the cudfs without streamz first, then investigate how the "example" df gets manipulated.

Yes, I already checked for cudf outside of streamz, and it seems to work fine.
