### ISSUE TITLE
groupby aggregate() function for SDFs 

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#303]
@martindurant, @CJ-Wright Currently, is there a way of performing an operation on SDFs involving multiple column aggregations after groupby like:
```
sdf.groupby('x').agg({'y':'sum', 'z':'mean'}) 
```
If not, any opinions on how difficult it would be to add this functionality?

**Comment by chinmaychandak** [comment]
Any thoughts here, @CJ-Wright / @martindurant?

**Comment by martindurant** [comment]
You can already do this now, by doing the two aggregates separately and merging them back into a single stream. Since each type of aggregation is achieved differently, it would probably be too onerous to write a generic groupby-agg function like this.

**Comment by chinmaychandak** [comment]
Wouldn't that be inefficient, though, since we'd have to perform groupby multiple times?

**Comment by martindurant** [comment]
I would have to check the implementation, but I would think the groups are updated per incoming datum and then passed to the agg class(es). You could make a custom agg class to only work on each group once.

**Comment by chinmaychandak** [comment]
Understood. Can you check if this would be the optimal way to merge two groupby-agg results?

```
import pandas as pd
from streamz import Stream
from streamz.dataframe import DataFrame

stream = Stream()
example = pd.DataFrame({'name': [], 'amount': [], 'other':[]})
sdf = DataFrame(stream, example=example).groupby(['name'])

s1 = sdf.amount.sum().stream
s2 = sdf.other.sum().stream

def merge(x):
    return pd.concat([x[0], x[1]], axis=1).rename({0:'amount', 1:'other'})

s1.zip(s2).map(merge).gather().sink(print)
```

**Comment by CJ-Wright** [comment]
I think that looks reasonable

**Comment by chinmaychandak** [comment]
Thanks @CJ-Wright

**Comment by CJ-Wright** [comment]
Full disclosure I haven't used streaming dataframes that much, so please take that with a grain of salt

**Comment by cheekybastard** [comment]
@chinmaychandak Another option, you can combine the two aggs in the groupby with apply/lambda.

```
import pandas as pd
from streamz import Stream
from streamz.dataframe import DataFrame

stream = Stream()
example = pd.DataFrame({'name': [], 'amount': [], 'other':[]})
sdf = DataFrame(stream, example=example)

def agg(df):
    return  df.groupby('name').apply(
        lambda x: {
            'amount': x['amount'].values.sum(),
            'other': x['other'].values.mean()
           })

sdf_agg = dfs.stream.map(agg).sink(print)
```

**Comment by chinmaychandak** [comment]
@cheekybastard Thanks for helping out, but I don't think this would work, since this is not maintaining cumulative state like SDFs do.
