### ISSUE TITLE
Update networkx

### ISSUE THREAD

**Issue by OpenCoderX** [python-streamz/streamz#313]

**Comment by CJ-Wright** [comment]
Can you provide a bit more context?

**Comment by OpenCoderX** [comment]
2.4 was released with some function removals and renames, I don't have a specific defect that needs resolved by updating but want to log this as a potential breaking change if we use any of the deprecated mothods or renamed methods. Maybe a better request is to lock the version streamz uses to 2.3 until 2.4 is tested.

**Comment by jsmaupin** [comment]
The only uses I'm seeing are `networkx.DiGraph()` and `networkx.find_cycle(...)`

**Comment by jsmaupin** [comment]
And, `networkx.relabel_nodes(...)`
