### ISSUE TITLE
Unable to use buffer after partition

### ISSUE THREAD

**Issue by roveo** [python-streamz/streamz#317]
# Demonstration

```py
from streamz import Stream

source = Stream()
source.partition(3).buffer(10).sink(print)

for i in range(20):
    source.emit(i)
```

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    source.partition(3).buffer(10).sink(print)
TypeError: 'list' object is not callable
```

# Why

`partition` overwrites `buffer` in `__init__`:
```py
    def __init__(self, upstream, n, **kwargs):
        self.n = n
        self.buffer = []
        Stream.__init__(self, upstream, **kwargs)
```

# Solution

Rename `partition.buffer` into something else.

**Comment by martindurant** [comment]
I am not sure I understand why the attribute name is a problem
*but* - your code here is, essentially, a test case. I would recommend you add it to the tests, and show that your proposed change makes it pass, and submit a new PR.

**Comment by roveo** [comment]
Will do.

> I am not sure I understand why the attribute name is a problem

In core.py buffer is registered as a method of Stream class. But when `partition` stream is constructed, `self.buffer` get overwritten. So you can't use buffer right after partition (and also timed_window and several other stream kinds that also overwrite buffer).

**Comment by martindurant** [comment]
aha, understood. Perhaps indeed rename all those instance attributes to `_buffer`.
