### ISSUE TITLE
Can't emit with metadata from custom Stream

### ISSUE THREAD

**Issue by roveo** [python-streamz/streamz#319]
I'm trying to emit messages with some metadata from a custom Stream. Getting this error:

```TypeError: _emit() got an unexpected keyword argument 'metadata'```

Here's the calling method:
```py
    async def do_poll(self):
        while not self.stopped:
            logger.info(f"Polling {self.table}")
            results = await self.loop.run_in_executor(None, self.query)
            metadata = self._self_metadata()
            metadata.update(dict(rowcount=len(results)))
            self._emit(results, metadata=[metadata])
            logger.info(
                f"Emitted {len(results)} rows, sleeping for {self.polling_interval}s"
            )
            await gen.sleep(self.polling_interval)
```

I tried to get the signature of `self._emit` and it returns `(x)` like it's not expecting any kwargs, which is weird because it's certainly in the `Stream` code.

The version is `0.5.2`.

Correction: it's actually a subclass of `Source` which is a subclass of `Stream`. It doesn't override  `_emit` so I'm expecting it to work the same.

**Comment by CJ-Wright** [comment]
you need to be working on the master branch. `0.5.2` doesn't have metadata handling. We haven't run a release with metadata handling yet.

**Comment by roveo** [comment]
OK, thanks!
