### ISSUE TITLE
Cut a new release to Anaconda

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#322]
With checkpointing and a few other important PRs merged, can we cut a new release?

**Comment by chinmaychandak** [comment]
I see a new release was cut. Any ETA on uploading on Anaconda yet?

**Comment by CJ-Wright** [comment]
should go up on conda-forge in about 30-60 mins https://github.com/conda-forge/streamz-feedstock/pull/10

**Comment by chinmaychandak** [comment]
Awesome, thanks a lot!

**Comment by chinmaychandak** [comment]
@CJ-Wright, @martindurant Would it be a good time now to cut a 0.5.4 release? When do we bump up to 0.6?

**Comment by martindurant** [comment]
On pypi now, coming to conda-forge soon.
I don't know about 0.6.0 - when we made a big change?
