### ISSUE TITLE
cannot reuse already awaited coroutine

### ISSUE THREAD

**Issue by roveo** [python-streamz/streamz#324]
I'm building an async stream and started getting this error:

```
future: <Future finished exception=RuntimeError('cannot reuse already awaited coroutine')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
RuntimeError: cannot reuse already awaited coroutine
```

It doesn't crash anything, but I'm still interested in how to prevent it.

Here's the structure of the stream:
![stream](https://user-images.githubusercontent.com/5427958/78269628-85085b80-7512-11ea-93d3-1e6311ba8b67.png)

The error only appears when I add the left hand of the stream (from get_metadata). My understanding is that without it there's only one sink and so each coroutine produced by the source is only awaited once. How do I handle multiple sinks in this case?

**Comment by martindurant** [comment]
Do all sinks get the expected data?

**Comment by roveo** [comment]
Yes, I tested this with a mock source that produces a fixed number of rows and it looks like all of them reach the target database even when there are these errors.
