### ISSUE TITLE
Best strategy to pass data from one stream to another

### ISSUE THREAD

**Issue by OpenCoderX** [python-streamz/streamz#326]
There are several methods to pass data through stream pipelines:
- calling emit on the target stream
- passing the source stream as an up stream to the initialize method of the downstream
- using the connect method passing the downstream as a parameter

I'm wondering in what scenarios we should prefer each strategy, are there any defined best practices around this question?

**Comment by jsmaupin** [comment]
Do you need to pass into another existing stream. I usually just create a branch like so:

```python
def dec(x):
    return x - 1

def inc(x):
    return x + 1

source = Stream()
stream = source.map(inc)
stream.sink(print)

# Branch into a different stream
stream.map(dec).sliding_window(2).sink(print)

for i in range(10):
    source.emit(i)
```

**Comment by OpenCoderX** [comment]
Does branching allow me to assign each branch a new name? I have a lot of streams from various external sources and like to namespace them, which is useful when export the graph as the name appears on the graph.

**Comment by jsmaupin** [comment]
This seems to work, but you do need to label every node in the stream. Although, each node in the pipeline is a streamz `Stream` object.

```python
source = Stream()
stream = source.map(inc)
stream.sink(print, stream_name='Main Stream')

# Branch into a different stream
stream.map(dec, stream_name='Stream 2')\
    .sliding_window(2, stream_name='Stream 2')\
    .sink(print, stream_name='Stream 2')

visualize(source)

for i in range(10):
    source.emit(i)
```

**Comment by martindurant** [comment]
Would it be good if, by default, a stream passes on its name to any of its children?

**Comment by OpenCoderX** [comment]
Without publishing too many details of my project these details might help, I have created:
- stream A that accepts messages from a websocket A, the websocket client has a callback method that calls emit on the stream A when a new message is received
- stream B that that accepts messages from a websocket B, the websocket client has a callback method that calls emit on stream B when a new message is received
- stream C that is initialized like so
```
union_stream = sz.combine_latest(*union_streams, emit_on=[*union_streams]).map(filter_cache_stream)
```

The application builds upon external data sources using that general patter: each external source gets it's own Stream when the app is started then they are combined and mapped through various calculations. As this app grows I'm looking to verify this is an acceptable pattern to follow. Is it common to call emit on a stream from the map method of a different stream?

**Comment by CJ-Wright** [comment]
Why not use `connect` directly?

**Comment by OpenCoderX** [comment]
@CJ-Wright That's a great question, I don't know! I guess that feeds into my original thought when opening this issue, what are the best practices around each method of connecting streams. What if one stream can possibly emit into 1 of 3 other streams based on an if statement in a Stream.map callback? Would it be better to connect all 3 to the upstream then ignore 2/3 messages in each downstream?

**Comment by CJ-Wright** [comment]
I wouldn't put the if statement in the map. I would do the connection and put in filer nodes in front of each sub pipeline.

Calling emit on a downstream node means the graph structure isn't preserved. All the nice things you get by having the graph (common event loop, nice chart making, etc.) are tied to having the relationships between the nodes be explicit.
