### ISSUE TITLE
How to pass additional style and color options to graphviz?

### ISSUE THREAD

**Issue by OpenCoderX** [python-streamz/streamz#332]
My application has many streams of different sources, how can I pass some additional style of color params to graphviz? FOr example I would like streams that start via xls files to be red, streams that start via xml files to be yellow and streams that take input from websockets to be blue. It would also be nice to pass color and style options to intermediate nodes like map, combine latest, etc. Is this possible?

**Comment by CJ-Wright** [comment]
Currently these are set as attributes on the classes, see https://github.com/python-streamz/streamz/blob/master/streamz/core.py#L156-L159

There are then plugged into graphviz here, https://github.com/python-streamz/streamz/blob/master/streamz/graph.py#L80-L84

In the future we might consider having a `_graphviz` dict and just unpack that into graphviz rather than having individual attributes.

**Comment by OpenCoderX** [comment]
Thanks! @CJ-Wright

**Comment by OpenCoderX** [comment]
@CJ-Wright Would you be interested in a pull request that adds an optional dict keyword arg called graphviz_styles that if supplied overwrites the static styles?

**Comment by martindurant** [comment]
Sounds reasonable to me

**Comment by CJ-Wright** [comment]
I think that would be great!

**Comment by badiku** [comment]
there are many options or parameters for function `graphviz.Digraph`,
like `graph_attr`, `node_attr`, `edge_attr`.
but currently,  in function `to_graphviz`, this line:
https://github.com/python-streamz/streamz/blob/f9b4ce38fc8251c3807387e37e935e157e07d0df/streamz/graph.py#L134
it pass only `graph_attr` .

to pass more options to function `graphviz.Digraph`,
I modified this line to:
```python
gvz = graphviz.Digraph(**graph_attr)
```

so as to add node_attr like fontname to support Other language.

```python
import graphviz
graphviz.Digraph?

Init signature:
graphviz.Digraph(
    name=None,
    comment=None,
    filename=None,
    directory=None,
    format=None,
    engine=None,
    encoding='utf-8',
    graph_attr=None,
    node_attr=None,
    edge_attr=None,
    body=None,
    strict=False,
)

```

**Comment by martindurant** [comment]
@badiku : that sounds reasonable (please submit a PR), but do note that the individual nodes and edges on the lines that follow have their own kwargs too, taken from node-specific attributes.
