### ISSUE TITLE
Checkpointing the state maintained within an SDF.

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#335]
Currently, Kafka checkpointing commits offsets after data has been processed, enabling a job to pick up from where it left off in case it has to restart. 

However, if the job maintains cumulative state across batches using an SDF, it loses the state if it restarts. To enable checkpointing of this state along with the Kafka topic offsets, we can [publish/update](https://distributed.dask.org/en/latest/publish.html) the SDF at the end of every batch as a dataset in distributed memory using Dask. 

My question is, how do we restart the job with the last saved SDF state? Is there an easy way to implement this, considering the SDF doesn't consider starting from any initial state? Any ideas?

**Comment by chinmaychandak** [comment]
@martindurant, any ideas here?

**Comment by martindurant** [comment]
Would the simplest solution be, then, to allow setting an initial state?

**Comment by chinmaychandak** [comment]
Yes. I will need to familiarize myself with the SDF code base first before implementing this. It should be a simple change, it seems, though. Any helps or tips would be appreciated!
