### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by cgi1** [python-streamz/streamz#337]
[Link for Repo Example](https://github.com/python-streamz/streamz/blob/master/examples/dataframes.ipynb)

```
p = (DataFrame({'raw': sdf.x,
                        'smooth': sdf.x.rolling('100ms').mean(),
                        'very-smooth': sdf.x.rolling('500ms').mean()})
     .plot(width=700)
    )
```
yields
`AttributeError: DataFrame has no attribute 'plot'`

**Comment by nils-braun** [comment]
Same for me. I would actually vote to either remove this notebook as it does not add a lot of benefits compared to the quite good documentation or to add more content to it.

**Comment by martindurant** [comment]
But it *is* nice :) So I fixed it instead.

**Comment by silvavn** [comment]
I just tested this any the hvplot seems to not be working again.

**Comment by martindurant** [comment]
What versions do you have, and what do you see?

**Comment by silvavn** [comment]
I have `jupyterlab 2.2.6`, 'hvplot 0.6.0' and, `bokeh 2.2`
 I just see an empty plot as mentioned:
![image](https://user-images.githubusercontent.com/37382997/91478663-7faf0300-e85d-11ea-88ce-6d661dfedfb1.png)

**Comment by amodwani** [comment]
@silvavn I tried your code as in screenshot hvplot seems to works.
<img width="1680" alt="Screenshot 2020-08-29 at 3 21 39 PM" src="https://user-images.githubusercontent.com/25533597/91634129-998e4880-ea0b-11ea-82bb-4366f7145bd1.png">

**Comment by amodwani** [comment]
@silvavn I tried your code it seems to work fine with master branch.
<img width="1677" alt="Screenshot 2020-08-29 at 3 25 11 PM" src="https://user-images.githubusercontent.com/25533597/91634172-f5f16800-ea0b-11ea-82b6-492064a34ad0.png">
