### ISSUE TITLE
can not set a eventloop to streamz

### ISSUE THREAD

**Issue by hsz1273327** [python-streamz/streamz#338]
when i set a asyncio eventloop to  streamz there is a error `'_UnixSelectorEventLoop' object has no attribute 'add_callback'` 

+ evn: pyhton3,7 

+ requirements:
structlog==19.1.0
streamz==0.5.2
cmp-version==3.0.0
confluent-kafka==1.3.0
hiredis==1.0.0
aredis==1.1.5
geoip2==3.0.0
msgpack==1.0.0
protobuf==3.11.3
grpcio==1.29.0
aiogrpc==1.7

+ code:
```python
...
def main(loop):
   ...
   source = Stream.from_kafka(value["in"], LISTENED_KAFKA_PARAMS, asynchronous=True,loop=loop)
        source.buffer(10000).map(lambda x: json.loads(x.decode("utf-8"))).filter(data_filter).sink(value["handdler"])
        sources[key] = source
    for source in sources.values():
        source.start()
    

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    main(loop)
    try:
        log.warn("process start")
        loop.run_forever()
    except KeyboardInterrupt:
        pass
    finally:
        loop.close()
        log.warn("process stoped")

**Comment by martindurant** [comment]
Since streamz has been around a while, it might need to be a tornado IO loop - but those can be made from asyncio loops, so a single lie for conversion should save you. https://www.tornadoweb.org/en/stable/asyncio.html#tornado.platform.asyncio.AsyncIOLoop

**Comment by hsz1273327** [comment]
thanks
