### ISSUE TITLE
How to create arbitrary amount of streams and pass to coroutine?

### ISSUE THREAD

**Issue by HolzmanoLagrene** [python-streamz/streamz#339]
I get data in via the following function:
```
async def capture_and_fetch(self, stream):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.connect((self.HOST, self.PORT))
            while True:
                data = sock.recv(1024)
                if not data:
                    break
                await stream.emit(data)
                await asyncio.sleep(0.1)
```

And i try to run this piece of code for different socketservers in "parallel" using asnycio:
```
if __name__ == '__main__':
   loop = asyncio.get_event_loop()
   streams = []
   for device in self.device_list:
      stream = Stream(asynchronous=True,stream_name=device.name, loop=loop)
      stream = stream.map(lambda x: device.put_together_stubs(x)).flatten(). \
             map(lambda x: device.remove_multipath_fading(x))
      streams.append(stream)
      loop.create_task(device.capture_and_fetch(stream))
```

And then combine the (minimally two streams) by applying
```
s = streams[0].union(streams[1])
s.sink(print)

loop.run_forever()
```

However, i notice that the stream defined in the main `function` was never really executed and instead the raw data is emitted two both streams and then united.

What am I doing wrong?

**Comment by HolzmanoLagrene** [comment]
Ok i got a bit further, but i still cant do what i actually want:

While this works:
```
source_1 = Stream(asynchronous=True, stream_name='source', loop=loop)
stream_1 = source_1. \
map(lambda x: self.device_list[0].put_together_stubs(x)). \
flatten(). \
map(lambda x: self.device_list[0].remove_multipath_fading(x))

source_2 = Stream(asynchronous=True, stream_name='source', loop=loop)
stream_2 = source_2. \
map(lambda x: self.device_list[1].put_together_stubs(x)). \
flatten(). \
map(lambda x: self.device_list[1].remove_multipath_fading(x))

stream_1.union(stream_2).sink(print)
loop.create_task(self.device_list[0].capture_and_fetch(source_1))
loop.create_task(self.device_list[1].capture_and_fetch(source_2))

```

This will always pass the object for `device` to the stream and not different objects:
```
streams = []
for device in self.device_list:
   source = Stream(asynchronous=True, stream_name='source', loop=loop)
   stream = source. \
                map(lambda x: device.put_together_stubs(x)). \
                flatten(). \
                map(lambda x: device.remove_multipath_fading(x))
   streams.append(stream)
   loop.create_task(device.capture_and_fetch(source))
```

Is there a way to create arbitrary streams and pass them to coroutines?

**Comment by nils-braun** [comment]
Hi @HolzmanoLagrene! 
I am not very deep into the streamz library already, but are you maybe having a problems with lambda capture (e.g. as described here https://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture) - which is unrelated to the stream library? Because if you pass a lambda function, the function will only store the pointer to "device", but device actually changes in the for loop, so in the end all device pointers will point to the same (last) object.
You can fix this as described in the link with a `partial` or with the mentioned "default-parameter-trick".

**Comment by martindurant** [comment]
@nils-braun I think is right, you should use a keyword parameter to evaluate the variable at the time of declaring the lambda
```
lambda x, device=device: device.put_together_stubs(x)
```
This may seem like it's no different, but the definition of a lambda is evaluated immediately, whereas nonlocal references in the body are only got at execution time.
