### ISSUE TITLE
Output cells not updating in jupyter lab

### ISSUE THREAD

**Issue by ehegenberger** [python-streamz/streamz#341]
So I just discovered [Jupyterlab cell output issue](https://github.com/python-streamz/streamz/issues/307), and was relieved to see I'm not going insane. I am very reluctantly switching my entire project to a notebook, but hopefully someone who understands what's going on can fix it for jupyter lab. Meanwhile, it would be __really great__ if someone who's responsible for things like this would put a notice in big cheerful letters on the front cover saying __"DO NOT TRY THIS IN JUPYTER LAB!"__ :)

I copied the streamz example from @mrocklin's slides at [streamz-walkthrough-to-dataframes.ipynb](https://gist.github.com/mrocklin/893e693ed19a357ea38962dcf112f616). When I get to cell 11:

`from tornado import gen
from tornado.ioloop import IOLoop

async def f():
    while True:
        await gen.sleep(0.100)
        record = create_record()
        await source.emit(record, asynchronous=True)
        
IOLoop.current().add_callback(f)`

the output cells update once and are then silent. If I set the log level to "Info," i can see that the function is running continuously in the background and generating data, but this is not reflected in the notebook cells. I have tried this using tornado and threading on Windows 10 and in Ubuntu under WSL, using streamz_dev.yml in each case. Under Windows 10, the cells will occasionally start updating if I run a simple command like threading.enumerate() multiple times, but if I then run a new cell to access the data, visible updating stops again. I have not been able to duplicate this behavior in WSL; there is simply no visible updating, even though it's evident from the log that the function really is running in the background. I also tried putting a progress bar widget in the same function, and it displays and updates perfectly even though there's still no visible data from the stream.

Has anybody gotten this to work on windows or WSL? Has anybody recently run it successfully on a linux machine? What am I doing wrong here?

**Comment by martindurant** [comment]
Have you run
`jupyter labextension install @jupyter-widgets/jupyterlab-manager` ?
I found that this made the display work, and that without it you get "odd" behaviour; but I am not on Windows.

Sorry for the slow reply here...

**Comment by martindurant** [comment]
OK, I saw your problem too. I find the following code does the right thing (but is not general, it assumes the type being passed). Note I have changed tornado->asyncio for my convenience.
```python
import asyncio
loop = asyncio.get_event_loop()

async def f():
    x = 0
    while True:
        await asyncio.sleep(0.100)
        x += 1
        s.output_ref().outputs = ({'output_type': 'display_data',
  'data': {'text/plain': str(x)},
  'metadata': {}},)

asyncio.run_coroutine_threadsafe(f(), loop)
```

**Comment by ehegenberger** [comment]
Thanks very much for tracking this down. I've since moved on to another project, but I'll be revisiting this again in a month or so and I do appreciate the help!
