### ISSUE TITLE
Windowing over time feature TODO

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#355]
While running some custreamz pipelines which require a window-over-time functionality, I came across a TODO in the existing streamz codebase [here](https://github.com/python-streamz/streamz/blob/239b807fd70848f851570463329662ce92c227a4/streamz/dataframe/aggregations.py#L211), which I wasn't able to understand. 

Is anyone familiar with what needs to be done here? I'm assuming this is not some sort of bug, but something which must be done to improve efficiency (maybe throughput or memory-utilization).

**Comment by martindurant** [comment]
I believe it is only stating that `.append()` is an inefficient process for dataframes, and can be avoided in this line, if the original dataframe has already become empty.
