### ISSUE TITLE
[BUG] Window operations return incorrect output if beginning/intermediate indexes are empty.

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#357]
The code below:
 
```
from streamz import Stream
from streamz.dataframe import DataFrame
import pandas as pd

# Only pass records with "amount" = 5 into the window, use the "ts" column as datetime index.
def preprocess(pdf):
    mask = pdf["amount"] == 5
    pdf = pdf.loc[mask]
    pdf["ts"] = pdf["ts"].astype("datetime64[ms]")
    pdf.index = pdf["ts"]
    return pdf

source = Stream()

stream = source.map(preprocess)

example = pd.DataFrame({"amount":[], "ts":[]})
sdf = DataFrame(stream=stream, example=example)

sdf.window("1h").amount.sum().stream.sink(print)

source.emit(pd.DataFrame({"amount":[1,2,3], "ts":["2050-01-01 00:00:00", "2050-01-01 01:00:00", "2050-01-01 02:00:00"]}))

source.emit(pd.DataFrame({"amount":[5,5,5], "ts":["2050-01-01 03:00:00", "2050-01-01 04:00:00", "2050-01-01 05:00:00"]}))
```

gives the output:

```
0
15
```

instead of 

```
0
5
```

If I replace the emits to:

```
source.emit(pd.DataFrame({"amount":[5,2,3], "ts":["2050-01-01 00:00:00", "2050-01-01 01:00:00", "2050-01-01 02:00:00"]}))

source.emit(pd.DataFrame({"amount":[5,5,5], "ts":["2050-01-01 03:00:00", "2050-01-01 04:00:00", "2050-01-01 05:00:00"]}))
```

the output is 

```
5
5
``` 
as expected.

I believe the issue is [here](https://github.com/python-streamz/streamz/blob/239b807fd70848f851570463329662ce92c227a4/streamz/dataframe/aggregations.py#L206): if the dataframe that enters the SDF-window op. is empty, then the deque that gets created/updated in the `diff_loc` causes issues.

Any suggestions on what would the best way to fix this?

**Comment by martindurant** [comment]
I could imagine changing
```
dfs.append(new)
```
to
```
if not new.empty:
    dfs.append(new)
```
(or perhaps put the empty ones directly into `old`?)

However, I must admit, I'd like you to explain perhaps in a couple of words why the output in your examples should be as it is, it isn't immediately obvious to me. For the first case, the first row that enters the window is the "2050-01-01 03:00:00" one, the window never sees the earlier rows.

**Comment by chinmaychandak** [comment]
> For the first case, the first row that enters the window is the "2050-01-01 03:00:00" one, the window never sees the earlier rows.

In the first case, the first `emit` followed by `preprocess` causes an empty dataframe to be added to the deque maintained by `diff_loc` inside the SDF window. The second `emit` followed by `preprocess` causes all 3 rows to be added to the deque. Now, the `1h` window should only consider the last 1 hour worth of data and move all the other records to `old`. But this doesn't happen, because the comparison of indexes fails because the first deque element is an empty dataframe/index.

In the second case, however, we can see that on the second emit, the elimination of older records (the record with `00:00:00` as well as the ones with `03:00:00`, `04:00:00`happens correctly, leading to the output to be the only valid record in the last hour (hence the answer 5).

**Comment by chinmaychandak** [comment]
Okay, so I made these changes in `diff_loc`:

```
    if len(new) > 0:
        dfs.append(new)
   .
   .
    if len(dfs) > 0:
        mx = max(df.index.max() for df in dfs)
        .
        .
```

I see that the test case above now produces correct results, but the existing test cases in `test_groupby_windowing_value` fail [here](https://github.com/python-streamz/streamz/blob/239b807fd70848f851570463329662ce92c227a4/streamz/dataframe/tests/test_dataframes.py#L753), because of some empty grouper values not being handled in `diff_align`. I am not familiar with this part of the code base, so will need some time digging in. @martindurant Any idea what would need to be handled in `diff_align`?

**Comment by chinmaychandak** [comment]
This is getting a little complicated to fix. Any help/insights would be much appreciated! :)

**Comment by martindurant** [comment]
This can be closed?
