### ISSUE TITLE
QUESTION: How to hvplot from csv file updated every 1 second

### ISSUE THREAD

**Issue by pybokeh** [python-streamz/streamz#361]
Hello
I have a very simple use case.  I have the following python script that just generates CPU usage of my machine every second and saves the data into a csv file.  I am trying to use the streamz library to then use this csv file as a source data and plot the data using hvplot library.

Here's my script for generating CPU usage date:
```
# pip install psutil
import csv
import psutil
import time

x_value = 0

fieldnames = ["x_value", "cpu_perc"]


with open('data.csv', 'w') as csv_file:
    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    csv_writer.writeheader()

while True:

    with open('data.csv', 'a') as csv_file:
        csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        y_value = psutil.cpu_percent()

        info = {
            "x_value": x_value,
            "cpu_perc": y_value
        }

        csv_writer.writerow(info)
        print(x_value, y_value)

        x_value += 1

    time.sleep(1)
```

Then in my jupyter notebook, I've tried:

```
import hvplot.streamz
import pandas as pd
from streamz import Stream

source = Stream.from_textfile('data/data.csv', poll_interval=1)
source.start()
example = pd.DataFrame({'x': [], 'cpu_perc': []})
sdf = source.to_dataframe(example=example)
sdf.hvplot()
```
But I get an emtpy bokeh chart.  I looked at the dataframe page in the documentation, but doesn't really show how to use a csv file.  I looked at the API docs and found the from_textfile() method from the Stream class and also found the to_dataframe() method, and just went from there.

**Comment by martindurant** [comment]
@chinmaychandak - an excellent example of the documentation being inadequate?

Perhaps it would be nice to have some sort of debug mode where, as an event travels through the graph, you can see what becomes of it at each node.

**Comment by chinmaychandak** [comment]
@pybokeh, I am not familiar with `hvplot`, but there's a couple of things in your code which I think are incorrect.

First, `from_textfile` returns the lines from a CSV file as strings, while an SDF expects the input as a Pandas dataframe as opposed to a string. An SDF is primarily used for cumulative aggregations/streaming computations, which does not seem to be the case here, so you might as well skip using SDFs altogether.

I would suggest using code like this instead:

```
import hvplot.streamz
import pandas as pd
from streamz import Stream
from streamz.dataframe import DataFrame

source = Stream.from_textfile('data.csv', poll_interval=5)

def preprocess(line):
    if line[0] == "x":
        return None
    tokens = line.strip('\n').split(',')
    x = tokens[0]
    cpu_perc = tokens[1]
    df = pd.DataFrame({'x': [x], 'cpu_perc': [cpu_perc]})    
    return df

def plot(df):
    if df is not None:
        df.hvplot()

source.map(preprocess).map(plot)

source.start()
```

**Comment by chinmaychandak** [comment]
> @chinmaychandak - an excellent example of the documentation being inadequate?
> 
> Perhaps it would be nice to have some sort of debug mode where, as an event travels through the graph, you can see what becomes of it at each node.

I agree! The docs are lacking here. A todo for our docs update sprint. :)

**Comment by martindurant** [comment]
@jbednar , you have an example exactly like this, right?

**Comment by jbednar** [comment]
Sort of, though my version (tornado_data_stream.ipynb in https://anaconda.org/jbednar/project/streaming_hvplot) doesn't use a CSV file. But I think we were about to make a new release of streamz that would make it a whole lot simpler.
