### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by martindurant** [python-streamz/streamz#364]
Any objections to a new release, to help with new plotting functionality and examples from the holoviz team?

**Comment by jsmaupin** [comment]
I'm just wondering how we're planing on incrementing the version number.

**Comment by martindurant** [comment]
Any preference? The actual value doesn't seem to have much meaning to me.

**Comment by jsmaupin** [comment]
Not too much.  I'm assuming that the number is `[major].[minor].[bug fix]`, where the minor version is incremented with new features such as the plotting functionality.

**Comment by CJ-Wright** [comment]
I would go with a single minor version bump. I don't think we broke API (or at least in a major way) but I wouldn't call this bug fix.

**Comment by martindurant** [comment]
In other dask-related projects, we've gone for something like [production-ready].[bigger changes].[smaller changes]. This would be a small change by that score.
We could discuss moving to something more rigorous.

**Comment by martindurant** [comment]
(we have no changelog or release notes either...)

**Comment by chinmaychandak** [comment]
I’m ok with a new release, although we might have to cut another release after #358 gets merged. It might take another week or so until I can remove the draft label from it.

**Comment by martindurant** [comment]
Done
