### ISSUE TITLE
Making the pipeline run forever (and how ensure_io_loop works)

### ISSUE THREAD

**Issue by roveo** [python-streamz/streamz#370]
Here's a simple example of a custom source.

```py
from streamz import Stream, Source
from tornado import gen


@Stream.register_api(staticmethod)
class from_range(Source):
    def __init__(self, n, **kwargs):
        self.n = n
        super().__init__(ensure_io_loop=True, **kwargs)

    async def run(self):
        for i in range(self.n):
            if self.stopped:
                break
            await self.emit(i)
            await gen.sleep(1)

    def start(self):
        self.stopped = False
        self.loop.add_callback(self.run)


src = Stream.from_range(10)
src.buffer(10).rate_limit(1).sink(print)

src.start()
```

This will exit immediately, which is obviously not what one wants, but also expected, because the loop will not wait for all callbacks to finish.

You can add this:

```py
async def run_forever():
    while True:
        await gen.sleep(10)

src.loop.run_sync(run_forever)
```

Which will cause this error from tornado:
```
RuntimeError: This event loop is already running
```

What's interesting is that if you pass `asynchronous=True` to the source, it will still be NOT asynchronous:

```py
src = Stream.from_range(10, asynchronous=True)

print(src.asynchronous)  # False
```

It looks like `ensure_io_loop` doesn't work as indended. Here's what the docs say:
```
    ensure_io_loop: boolean
        Ensure that some IOLoop will be created.  If asynchronous is None or
        False then this will be in a separate thread, otherwise it will be
        IOLoop.current
```

If I force `asynchronous=True` in `__init__`, it works:

```py
...
        super().__init__(asynchronous=True, **kwargs)
...
src.loop.run_sync(run_forever)  # actually runs forever
```

I think the problem (if there IS a problem) is in this piece of code, which I can't really wrap my head around:

https://github.com/python-streamz/streamz/blob/e24d0ba1509ed934e11c79c9a4f1f815664a9503/streamz/core.py#L173-L178

So my question is: what don't I understand and how do I make my pipeline run forever, possibly also with built-in sources (e.g. from_tcp, which doesn't even pass any kwargs to Stream).

I guess I could just create a second loop in another thread and `run_sync(run_forever)` in it, but it seems like an ugly solution.

**Comment by roveo** [comment]
I guess I could just create a second loop in another thread and `run_sync(run_forever)` in it, but it seems like an ugly solution.

**Comment by roveo** [comment]
It looks like if `ensure_io_loop` is True, the loop will always start in a thread, regardless of `asynchronous` value.

**Comment by martindurant** [comment]
Please compare with the following:
```python
@Stream.register_api(staticmethod)
class from_range(Source):
    def __init__(self, n, **kwargs):
        self.n = n
        super().__init__(ensure_io_loop=True, **kwargs)

    async def run(self):
        for i in range(self.n):
            if self.stopped:
                break
            self._emit(i)
            await gen.sleep(1)
        self.stopped = True

    def start(self):
        self.stopped = False
        self.loop.add_callback(self.run)


src = Stream.from_range(10)

out = src.buffer(10).rate_limit(1).sink_to_list()

src.start()
```

The main difference is the emit line: you can either call `_emit` like this, or `self.emit(i, asynchronous=True)`. Is is async, because its being called in an async function. The "typical" form in this codebase is to use tornado coroutines, which allow for `yield self._emit()` as in the TCP example. 

Note that this will run in the REPL fine, but does not contain waiting logic. Since the code is running in another thread, you can simply do

```python
while not src.stopped:
    time.sleep(1)
```
(there is a function `wait_for` that does this kind of thing).

For the async version, you should create your own loop and pass it, so that you can do `loop.run_until_complete` with `await_for`. See the TCP tests in test_sources.

@chinmaychandak : anything to add along the lines of "better documentation" ?

**Comment by roveo** [comment]
Thank you! This became much more clear.

I missed the `asynchronous` kwarg of `emit` completely. And the fact that I can just wait forever with a `while True` loop in the main thread and not worry about io loops. In my case though, I need an ioloop for other things, so I guess I'll just pass it to the source then.

**Comment by martindurant** [comment]
Yeah, the doc should specify that, to run async, the *same* loop needs to be used by the stream nodes and your code; but it is actually fine to have separate event loops in separate threads, but this wouldn't count as asynchronous=True mode. You can see various checks for the thread identity in the code.

OK to close?

**Comment by chinmaychandak** [comment]
> anything to add along the lines of "better documentation" ?

Nothing to add here from my side apart from what you've said already, although I'm sure we will find a few more places in the docs where we should update.

**Comment by roveo** [comment]
> OK to close?
Yes, problem solved. Thanks again!
