### ISSUE TITLE
AttributeError: module 'pandas.compat' has no attribute 'string_types'

### ISSUE THREAD

**Issue by badiku** [python-streamz/streamz#373]
today I got this error:
`AttributeError: module 'pandas.compat' has no attribute 'string_types'`

and the code is here:

https://github.com/python-streamz/streamz/blob/f9b4ce38fc8251c3807387e37e935e157e07d0df/streamz/dataframe/core.py#L248

the problem is , there's no pd.compat.string_types now.

pandas removed it at Mar 29, 2019, see here:
https://github.com/pandas-dev/pandas/pull/25903

**Comment by martindurant** [comment]
Missed this depr, thanks for posting.
Should be changed to
```python
if (isinstance(c, str) and c.isidentifier()))
```

Would you care to submit this fix as a PR?

**Comment by martindurant** [comment]
(also a test which uses `dir()` on a dataframe would be useful, as this should have been caught before)
