### ISSUE TITLE
CI things

### ISSUE THREAD

**Issue by CJ-Wright** [python-streamz/streamz#382]
We most likely need go get off Travis, so we should figure out how to do that.

Current proposals include:
- use conda-forge's system
- github actions

@martindurant

**Comment by martindurant** [comment]
Ref: https://github.com/dask/community/issues/107

**Comment by martindurant** [comment]
Looking for volunteers...
With any luck, changing the CI will also fix the kafka test that times out on travis (but passes locally).

**Comment by jrbourbeau** [comment]
Can this be closed? It looks like CI was migrated to GitHub actions in https://github.com/python-streamz/streamz/pull/402/files and Travis was removed in https://github.com/python-streamz/streamz/pull/403
