### ISSUE TITLE
Acknowledging messages from messaging systems

### ISSUE THREAD

**Issue by roveo** [python-streamz/streamz#391]
I'm working on implementing streamz sources for some messaging systems (Redis streams and GCP pubsub, will be available as plugins). The problem that came up is that I need to know when messages were succesfully processed (meaning, went through a sink) to acknowledge them to a messaging system.

There's a section on checkpointing and reference counting in the docs, but it's not entirely clear how to use it. Would you give me some directions?

**Comment by martindurant** [comment]
Yes, reference counting would be the thing you want - when references go to zero, the item has exited all nodes.
@chinmaychandak , would you like to provide an example of usage?

**Comment by martindurant** [comment]
PS: great to hear of the new source nodes!

**Comment by chinmaychandak** [comment]
This is absolutely amazing! Please check out [this](https://medium.com/rapids-ai/checkpointing-through-reference-counting-in-rapids-custreamz-f9ded03674f5) blog by @jsmaupin on how we implemented checkpointing through reference counting in streamz. It has a couple of good examples on how the ref counters are maintained in both sync and async nodes. Hope this helps!

**Comment by roveo** [comment]
Thanks, this blog post answered my questions :)
