### ISSUE TITLE
Redis plugin

### ISSUE THREAD

**Issue by roveo** [python-streamz/streamz#392]
As promised :)

[Repo](https://github.com/roveo/streamz_redis)
[Docs](https://streamz-redis.readthedocs.io/)

In the plugins PR, we talked about adding plugins as repos under python-streamz. Let's decide what/how to do here.

There should probably also be:

- CI with Github Actions — after/if it's moved to another repo
- python package on PyPi
- an extra in streamz for installing this

I'll make a PR once it's decided what to do.

**Comment by martindurant** [comment]
I definitely think you want to write a blog about this functionality.

I personally think this definitely ought to go into python-streamz as soon as you think it is ready for the public. Are you comfortable building and pushing your own pypi and conda-forge packages? There is no reason to wait for the streamz maintainers' permission.

> an extra in streamz for installing this

This one we can debate. I can see why you would want to have the core streamz package at least reference the possibility of the new plugins; but it's not obvious that the core package should be the reference point for such things.
cf: 
- intake uses entrypoints for plugins, but the code does not reference any external plugins, there is a doc page as an informal list of known plugins https://intake.readthedocs.io/en/latest/plugin-directory.html
- fsspec has an explicit dict of known implementations in the code and no entrypoints, so every new implementation needs to include a PR to fsspec and an evaluation by the maintainers, even when in a separate repo.

**Comment by roveo** [comment]
> I definitely think you want to write a blog about this functionality.
There's a couple of tutorials in the docs. I could write a blog too, but I don't know where that would go (in terms of visibility).

> I personally think this definitely ought to go into python-streamz as soon as you think it is ready for the public.
OK, I'll run it in prod for some time to see if there're any overlooked problems and come back with this.

> Are you comfortable building and pushing your own pypi and conda-forge packages?
Sure, will do.

> but it's not obvious that the core package should be the reference point for such things
I was thinking of the way it's done in Airflow, where "official" contrib packages are installed via extras. Surely you don't want to add every possible plugin to extras (and maybe not this one), but generally if something is widely used and considered reliable (and is under python-streamz org), it can go to extras. The point of plugins is keeping core dependencies slim, so maybe even some functionality that's currently in core should go into plugins (looking at you, Kafka!).

But there's not really much difference between `pip install streamz_smth` and `pip install streamz[smth]`, so I don't have a strong preference.

**Comment by martindurant** [comment]
(@roveo , it is Thanksgiving in the USA - but not here in Canada - so expect other people to be slow to reply)

**Comment by martindurant** [comment]
> But there's not really much difference between pip install streamz_smth and pip install streamz[smth], so I don't have a strong preference.

I actually prefer the former, because it would line up better with conda installation use, which will certainly be the normal route for our CUDA-using friends.

**Comment by roveo** [comment]
About PyPi/Conda packages: I can't do that without a Streamz release. PyPi doesn't allow direct git dependencies, so I need to refer to an existing version of Streamz.

**Comment by martindurant** [comment]
On pypi, you *can* refer to a version that doesn't yet exist, but I see no reason to create a new release.

**Comment by roveo** [comment]
OK, will wait until then. I'll close this and get back with a PR.
