### ISSUE TITLE
Error: dask w/ 2 streamz

### ISSUE THREAD

**Issue by wwoods** [python-streamz/streamz#397]
Expected: below program should run fine, or crash after printing `"exiting"`.

```python
import dask.distributed
import streamz

if __name__ == '__main__':
    with dask.distributed.Client() as client:
        s1 = streamz.Stream()
        s1o = s1
        s1o = s1o.scatter()
        s1o = s1o.map(lambda x: x+2)
        s1o = s1o.buffer(80)
        s1o = s1o.gather()

        s2 = streamz.Stream()
        s2o = s2
        s2o = s2o.scatter()
        s2o = s2o.map(lambda x: x+3)
        s2o = s2o.buffer(80)
        s2o = s2o.gather()

        rc = streamz.RefCounter()
        for _ in range(1000):
            s1.emit(_)
            s2.emit(_)
        print('exiting')
```

Actual: program crashes with below; exiting wasn't printed:

```
$ python dask_streamz_crash2.py
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fbcb7e54d60>>, <Future finished exception=CancelledError('lambda-8900fe7fe84a7a9105ea61c47a62abb4')>)
Traceback (most recent call last):
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/core.py", line 1168, in cb
    yield self._emit(x, metadata=metadata)
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 526, in callback
    result_list.append(f.result())
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/streamz/dask.py", line 144, in update
    result = yield client.gather(x, asynchronous=True)
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/walt/.conda/envs/py38streamz/lib/python3.8/site-packages/distributed/client.py", line 1852, in _gather
    raise exc
concurrent.futures._base.CancelledError: lambda-8900fe7fe84a7a9105ea61c47a62abb4
```

Versions: python==3.8.5, dask==2.30.0, streamz==0.6.1

**Comment by martindurant** [comment]
Was there any error output from the dask worker(s)?

**Comment by wwoods** [comment]
I'm not entirely sure what you mean -- that's the entire stdout/err output, and the `localhost:8787` interface logs don't show any errors or the like.

Notably, nothing else happens -- the program doesn't exit, it just hangs.

**Comment by wwoods** [comment]
I do wonder if this has something to do with the difference between `client.submit` and `dask.delayed`. Specifically, https://distributed.dask.org/en/latest/task-launch.html indicates that such a hang might occur with `client.submit` but that dask has special machinery to prevent hangs when using `dask.delayed`.

**Comment by wwoods** [comment]
Notably, replacing lines in `DaskStream.map.update` with:

```python
        #result = client.submit(self.func, x, *self.args, **self.kwargs)
        import dask
        result = dask.delayed(self.func, *self.args, **self.kwargs)(x).persist()
```

Then the example works. I'm not sure if the call to `persist` ruins the dask task graph's ability to optimize, however. The docs indicate that, in a distributed context, `persist` calls [will be computed asynchronously](https://docs.dask.org/en/latest/api.html#dask.persist).

**Comment by martindurant** [comment]
> dask.delayed(self.func, *self.args, **self.kwargs)(x).persist()

can you try with `client.compute(dask.delayed(self.func, *self.args, **self.kwargs)(x))` ?

**Comment by wwoods** [comment]
That's the same as `dask.delayed(self.func, *args, **self.kwargs)(x).compute()`. One's a shorthand for the other. I did explicitly try both, however. Same behavior.

**Comment by martindurant** [comment]
no, `.compute()` is blocking, `client.compute()` (as opposed to `dask.compute`) returns a future.

**Comment by wwoods** [comment]
Ah, that's a bit incongruous. I see though, I did use dask.compute, I think.

`client.compute` results in the original error on this issue.

**Comment by wwoods** [comment]
PS, if you didn't see my edit, the `.persist()` call never gets resolved during `gather()`, so it functionally NOPs the stream. I have to do other things for awhile, but will look again perhaps on Monday.

**Comment by wwoods** [comment]
Ah, I see the issue. Futures with the same key behave poorly, so it's important to not use a hash for non-pure or multiple emissions, which scattering as a list instead of a dict does. Replacing lines in `scatter.update` as follows fixes both this and #394:

```python
        #tokenized_x = f"{type(x).__name__}-{tokenize(x)}-{p}"
        #future_as_dict = yield client.scatter({tokenized_x: x}, asynchronous=True)
        #future = future_as_dict[tokenized_x]
        future_as_list = yield client.scatter([x], asynchronous=True, hash=False)
        future = future_as_list[0]
```

However, @martindurant you clearly know more Dask, so maybe there's a good reason not to do this?

**Comment by wwoods** [comment]
Notably, this solution *also* obviates the need for setting `pure=False` in the first place, which is probably "more correct" in the context of the streamz library specifically. It's certainly the less surprising behavior within a streaming idiom.

**Comment by chinmaychandak** [comment]
I'm no Dask expert but I remember that `scatter.update` was changed by #349. Martin would definitely know more.

**Comment by wwoods** [comment]
Right -- it looks like there were two choices, dict and list, and they chose to re-implement Dask's internal approach, which would be fine as long as every element being scattered resulted in a unique key. When the elements being scattered don't have unique keys, it causes problems with streamz. Even if the non-uniqueness bugs could be fixed while keeping the dict approach, unique elements and caching is also just a harder paradigm for users to wrap their heads around.

Pretty easy PR w/ a regression test, if the change looks good and like it won't break anything else.

**Comment by martindurant** [comment]
Seems like a reasonable thing to try, if all existing tests pass.
Thanks for digging, @wwoods .
cc @nils-braun
