### ISSUE TITLE
Stream methods on DaskStream lose daskiness

### ISSUE THREAD

**Issue by mrocklin** [python-streamz/streamz#4]
Inherited methods on DaskStreams produce Streams

```python
>>> type(source.to_dask())
DaskStream
>>> type(source.to_dask().buffer(10))
Stream
```

Somewhat related to #2

**Comment by kszucs** [comment]
Meta programming or a lot of code duplication or drop `stateful methods as classes`?
I'm curious of your solution.

**Comment by CJ-Wright** [comment]
I think the current approach has been to duplicate most of the base classes for dask classes as appropriate. I'd be interested in a more compact approach but I don't think that it impacts us that badly right now.
