### ISSUE TITLE
FEATURE: user events

### ISSUE THREAD

**Issue by martindurant** [python-streamz/streamz#407]
A source of events for streamz that would be interesting to implement, is the user.
We could pipe events from pyqt (i.e., a `slot`) to streamz, or from the browser using, for example, holoviews/panel
(see https://github.com/intake/filesystem_spec/blob/master/fsspec/gui.py#L14 for an interface to panel events that looks a lot like qt).

Since these things have their own even loops, a callback would need to hold the event loop associated with streamz, and call ~`loop.call_soon_threadsafe`~ `run_coroutine_threadsafe` (unless the loop can be shared - but this will still work).

**Comment by martindurant** [comment]
Further on holoviews, etc.: that stack already has a streaming, event processing model around `Param`, which has various listeners and event responders mostly, but not necessarily, based on browser events from a BokehServer. Since that server is Tornado, everything should interoperate nicely (although I *think* the holo-stack is mostly blocking functions, not async).

So you could have
- stream of tap events from the browser
- feed to scikit-multiflow (now River - very streamy) to predict next event
- plot back the current average velocity and prediction to the browser

( @philippjfr )

**Comment by philippjfr** [comment]
>although I think the holo-stack is mostly blocking functions, not async

That's mostly down to my unfamiliarity with async stuff, which is something I'm slowly trying to resolve, e.g. I did recently add support for registering async callbacks on `parameterized.param.watch` callbacks. It **should** therefore be possible to do. I'd love to explore this and resolve any issues as they crop up.

**Comment by martindurant** [comment]
Happy to help with asyncing. Indeed, this specific linkage holo-streamz might be the perfect use case.

**Comment by martindurant** [comment]
Examples in https://github.com/martindurant/streamz-q
