### ISSUE TITLE
Attempting to plot DataFrame causes stream to stop updating

### ISSUE THREAD

**Issue by ErstBlack** [python-streamz/streamz#408]
While streaming from a growing csv, it seems as if attempting to plot the DataFrame that I'm creating causes the source to stop updating.

For my environment, I have 2 jupyter notebooks, one creating the csv by appending one row per second, and the other reading from it.

Creating:
```python
import numpy as np
import pandas as pd
import time

df = pd.DataFrame({"Count": np.arange(0,200), "B": np.arange(200,600,2), "C": np.arange(600,200,-2)})
    
for x in range(len(df.index)):
    with open(target_csv, 'a') as f:
        pd.DataFrame(df.iloc[x]).T.to_csv(f,header=False, index=False)

    time.sleep(1)
```

Reading:
```python
import pandas as pd
from streamz import Stream
from streamz.dataframe import DataFrame
import hvplot.streamz

example = pd.DataFrame({'Count': [], 'B': [], 'C': []})
columns=['Count', 'B', 'C']
to_pd_df = lambda x: pd.DataFrame([x.strip().split(',')], columns=columns)

source = Stream.from_textfile(target_csv, start=True, from_end=True)
sdf = source.map(to_pd_df).to_dataframe(example=example)[['Count','B','C']]
sdf = sdf.set_index(sdf['Count'])[['B','C']]
```

While these are running, I'm able to run ```sdf.tail()``` to see the values updating in realtime.

```
Count    B     C
  199  598   202
```

However, the moment I try to create a visualization from this:

```python
DataFrame({'Increasing': sdf['B'],
           'Decreasing': sdf['C']}).hvplot()
```
or
```python
DataFrame({'Increasing': sdf['B'],
           'Decreasing': sdf['C']}).plot()
```
I get an empty Bokeh plot and the sdf.tail() stops updating.

**Comment by martindurant** [comment]
Unfortunately, the plotting only works with numerical types, and you have not converted the numbers read from the file. The following works OK.


```python
example = pd.DataFrame({'Count': [1], 'B': [1], 'C': [1]})  # <- give real values here
columns=['Count', 'B', 'C']
to_pd_df = lambda x: pd.DataFrame([
    [int(bit) for bit in x.strip().split(',')]  # <- make integers
], columns=columns)

source = Stream.from_textfile("target_csv", start=True, from_end=True)
sdf = source.map(to_pd_df).to_dataframe(example=example)[['Count','B','C']]
sdf = sdf.set_index(sdf['Count'])[['B','C']]
sdf
```

@philippjfr : This caused an error during plotting, which either broke the comm or the event loop. I found that the source could be restarted. Would turning on some logging somewhere have revealed this?

**Comment by philippjfr** [comment]
Hmm, in more recent versions of the HoloViz we should see errors piped to the output cell, if that's not happening that's a bug. Is there somewhere where we could make the event loop more robust to errors so it doesn't need to be restarted entirely?

**Comment by martindurant** [comment]
The restart I referred to is of the stream object - I don't think this changes the event loop. This, after a little consideration, suggests to me that maybe the exception happens where streamz passes the dataframe parts off to hvplot. Maybe neither side would catch that failure? 

In `hvplot.converter.HoloViewsConverter._process_data`:
```
            data.stream.gather().sink(self.stream.send)
```
maybe this should be replaced by a function with try/except and logging. Also, I would suggest that the `data.example` should *not* be included in the plot.
