### ISSUE TITLE
dask summit talk?

### ISSUE THREAD

**Issue by martindurant** [python-streamz/streamz#413]
https://summit.dask.org/present/

I think that streamz should be represented at the summit. Perhaps @chinmaychandak @jsmaupin could talk about high-throughput realtime kafka processing with cuDF. Perhaps @roveo has some redis-streamz-dask example.

**Comment by jsmaupin** [comment]
Oh, this is a great opportunity!  I would be more than happy to contribute here.

**Comment by mrocklin** [comment]
+1

**Comment by chinmaychandak** [comment]
This would be awesome. Thanks for bringing this to our attention, Martin!

**Comment by martindurant** [comment]
Time to the deadline, March 28th, is short, I'm afraid

**Comment by chinmaychandak** [comment]
Already wrote up a draft proposal, and it's under review - so should be able to submit in time, hopefully.

**Comment by martindurant** [comment]
Thanks for the interest, I'll close this issue now.
