### ISSUE TITLE
Adding map streams iteratively using a local lambda parametrized by the iterate value masks all previous iterations with final one

### ISSUE THREAD

**Issue by taylorm0192** [python-streamz/streamz#414]
Perhaps this is a core issue with Python and how local lambdas work.  But it does seem like a bug.  The DAG looks correct and each stream has a unique memory id (when assigned to a variable--not shown in this example).  I also set the stream_name to make sure that is not being masked somehow.  It just seems that when it's used as a fixed parameter in the lambda expression, it gets masked by the final iterate.

`    
    from streamz import Stream
    from functools import partial

    if __name__ == "__main__":
        s=Stream()
        names=['ibm', 'zroz']
        data=[{'ibm':('ibm', 100),
               'zroz': ('zroz', 10)},
              {'ibm': ('ibm', 50),
               'zroz': ('zroz', 5)}]
    
        # Method 1 - using local lambda expression with iteration
        for name in names:
            s.map(lambda _: _[name], stream_name=name).sink(lambda _: print(f'[1] {_}'))
    
        # Method 2 - using explicit callable with iteration
        def func_map(name, _):
            return _[name]
        for name in names:
            s.map(partial(func_map, name), stream_name=f'{name}_2').sink(lambda _: print(f'[2] {_}'))
    
        # Method 3 - using local lambda expression with explicit literals
        s.map(lambda _: _['ibm'], stream_name='ibm_3').sink(lambda _: print(f'[3] {_}'))
        s.map(lambda _: _['zroz'], stream_name='zroz_3').sink(lambda _: print(f'[3] {_}'))
    
        s.visualize("./map_lambda_bug_dag_1.png")
    
        for k, d in enumerate(data):
            print(f"Emission #:{k}")
            s.emit(d)`

> Emission #:0
[1] ('zroz', 10) // this should be ('ibm', 100)
[1] ('zroz', 10)
[2] ('ibm', 100)
[2] ('zroz', 10)
[3] ('ibm', 100)
[3] ('zroz', 10)

> Emission #:1
[1] ('zroz', 5) // this should be ('ibm', 5)
[1] ('zroz', 5)
[2] ('ibm', 50)
[2] ('zroz', 5)
[3] ('ibm', 50)
[3] ('zroz', 5)

**Comment by martindurant** [comment]
In the following, 
```
s.map(lambda _: _[name])
```
you effectively get something like the following function
```
def unnamed(_):
    name = globals()["name"]
    return _[name]
```
The point is, that the extraction of "name" from its scope only happens a run-time, not at definition time.  This is as opposed to the "explicit" version, where you *pass* the name rather than rely on the surrounding scope.

If you want to do this with lambdas, and have the variable evaluated at define time, the best idea is to use kwargs:
```
s.map(lambda _, name=name: _[name])
```
where the value of the optional kwarg is immediately evaluated, and then used as a local variable.

**Comment by taylorm0192** [comment]
That's very helpful, thank you!
