### ISSUE TITLE
How to access metadata in downstream functions?

### ISSUE THREAD

**Issue by scherand** [python-streamz/streamz#416]
I am trying to emit some metadata into a `streamz` pipeline and reading the same in a downstream function. Basically what I am doing is:

```python
stream = streamz.Stream()
mapped = stream.map(<myfunc>, myarg=<value>).sink_to_list()

stream.emit(<val>, metadata=[{"key": <metaval>}])

def <myfunc>(d, metadata=None, myarg=None):
    mv = metadata[0].get("key")  # <-- I have tried many variations of this
```
But `metadata` is `None` inside of `<myfunc>`, whereas `myarg` is not.

How can I access the (list of) metadata in `<myfunc>`? Or did I understand something incorrectly?

**Comment by martindurant** [comment]
I'm afraid that is not what metadata does - it is extra information passed to the implementation class, use possibly for the classes internal state.

For example, in `streamz.core.map.update`:
```python
    def update(self, x, who=None, metadata=None):
        try:
            result = self.func(x, *self.args, **self.kwargs)
        except Exception as e:
            logger.exception(e)
            raise
        else:
            return self._emit(result, metadata=metadata)
```
the metadata is simply passed on downstream, not to the mapping function. You could see how you could write a version of this to pass the metadata to the function too, perhaps using `inspect` to see if it would be a valid kwarg to pass.

Also, in `streamz.utils_test` there is a `metadata` class, which you could use to turn metadata into data, if you like. That class maybe could be promoted to the user API.

**Comment by martindurant** [comment]
@chinmaychandak , where is this documented?

**Comment by chinmaychandak** [comment]
@jsmaupin had added some documentation as part of the checkpointing PR [here](https://streamz.readthedocs.io/en/latest/core.html#metadata). 

I think this is one of the many areas where we can add more docs as part of #359.

**Comment by martindurant** [comment]
What do you think about promoting `metadata` (the node class) from tests to the main API?
