### ISSUE TITLE
Execution terminates early with Dask.distributed

### ISSUE THREAD

**Issue by WilliamCVan** [python-streamz/streamz#424]
```
    from time import sleep
    import time
    import timeit
    from dask.distributed import Client

    def inc(x):
        sleep(1)  # simulate actual work
        return x + 1

   if __name__ == '__main__':
    client = Client()
    source = Stream()
    source.scatter().map(inc).buffer(5).gather().sink(print)  # numbers 5-10 get cutoff and not printed

    starttime = timeit.default_timer()
    for i in range(10):
        source.emit(i)

    print("The time difference is :", timeit.default_timer() - starttime)

    client.close()
    print("done")

```

I'm having an issue where the last emits are getting cut off, so numbers 5-10 are not getting printed at all. The call is exiting even though there are items in the buffer. How do I prevent the execution from moving to print("done") until all numbers are processed? I'm getting this error due to early termination:

```
1
2
3
4
The time difference is : 1.1211735000000012
distributed.worker - WARNING - Heartbeat to scheduler failed
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x0000025263D613C8>>, <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed')>)
Traceback (most recent call last):
  File "C:\Users\Admin\.conda\envs\PyTorchENV\lib\site-packages\distributed\comm\tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
tornado.iostream.StreamClosedError: Stream is closed
...
done
```

**Comment by WilliamCVan** [comment]
The time.sleep is too slow and removing the buffer would cause things to execute synchronously which is also a no go. The reference counting was mentioned for Kafka, although I am not using it. 

If I switched to async API, that would pretty much mean not using the Streamz library...for my example above at least?

**Comment by martindurant** [comment]
> The time.sleep is too slow

I'm not sure I follow; but you can have your pipeline output to some other object you can watch and wait on that, like:
```
watchlist = []
source.scatter().map(inc).buffer(5).gather().sink(watchlist.append)
...
while len(watchlist) < 10
    time.sleep(0.01)
```

> The reference counting was mentioned for Kafka, although I am not using it.

Yes, it was developed for that use case, but doesn't require it.

> If I switched to async API, that would pretty much mean not using the Streamz library...for my example above at least?

Stream does support async and is implemented with async internally

**Comment by WilliamCVan** [comment]
Thanks for the sleep watchlist example, I think I'll go with that solution for my use case
