### ISSUE TITLE
from_kafka doesn't work with oauth based authentication

### ISSUE THREAD

**Issue by pthalasta** [python-streamz/streamz#431]
Implementation of the class `from_kafka` in the sources script uses `self.consumer.get_waterrmark_offset()` (https://github.com/python-streamz/streamz/blob/master/streamz/sources.py#L455) to fetch the offsets of the topic that is being used with streamz does not work with oauth based authentication and seems to be redundant.

As confluent kafka does not establish a connection with `get_watermark_offsets()` this results in a blocked thread loop that never exits and never establishes a connection. I've also filed a case with confluent regarding the same https://github.com/edenhill/librdkafka/issues/3556

If `self.consumer.get_waterrmark_offset()`  is redundant in implementation of the class `from_kafka`, it can probably be removed?

**Comment by martindurant** [comment]
I don't think there's much that we can do about it from our side. Getting watermarks will be necessary, in order to know which messages to read.

**Comment by pthalasta** [comment]
@martindurant i see your point, but `from_kafka` never uses the offsets returned by watermark. So, its based on the offset defined in the Kafka Consumer config? I totally agree its required in other implementations but i'm not sure if https://github.com/python-streamz/streamz/blob/master/streamz/sources.py#L455 is required?

**Comment by martindurant** [comment]
Oh right; I was probably thinking of the batched kafka sources (which will need this!). So for this specific source it might be OK to just drop it.

**Comment by pthalasta** [comment]
Yes, a probable fix for the rest should come from confluent based on the issue mentioned in the description.

**Comment by prodo56** [comment]
@martindurant as a fix for this issue, i made changes to the source.py for kafka input. Could you please review https://github.com/python-streamz/streamz/pull/438 and merge the changes to allow using kafka broker with oauth authentication.
