### ISSUE TITLE
Can a stream emit two messages for each one received?

### ISSUE THREAD

**Issue by poldpold** [python-streamz/streamz#447]
I'm kind of a newbie to ```streamz``` so please bear with me. I'm looking for a clean solution to input some data into a stream, and receive two pieces of data out, in a sequential fashion. I'm thinking of something like this:
```
from streamz import Stream

s = Stream()
ss = ???
sss = ss.map(print)
s.emit(1)
```
where after filling in ```???``` correctly, I would see a print of say 1 and 2, always in this order. Any suggestions?

**Comment by martindurant** [comment]
The very simplest thing you could do looks like
```
In [11]: s = streamz.Stream()

In [12]: s.sink(print)
Out[12]: <sink: print>

In [13]: s.map(lambda x: x + 1).sink(print)
Out[13]: <sink: print>

In [14]: s.emit(1)
1
2
```

The reason this works, and always preserves order, is that downstream nodes of `s` (a `sink` and a `map`) are called in the same order as they were created.

Perhaps you wanted something more than `print` to process the two events together. Whereas you could, of course, have created a mapper function in one go, here is a slightly more complicated graph:
```
In [15]: s = streamz.Stream()

In [16]: s2 = s.map(lambda x: x)  # process unmodified event

In [17]: s3 = s.map(lambda x: x + 1)  # process and modify event

In [18]: s4 = s2.zip(s3)  # join events for further processing

In [19]: s4.sink(print)
Out[19]: <sink: print>

In [20]: s.emit(1)
(1, 2)
```

**Comment by poldpold** [comment]
Thanks @martindurant, I see now. It's much easier than I thought.
